### ISSUE TITLE
Support for literals from Shopify liquid

### ISSUE THREAD

**Issue by danielfriis** [harttle/liquidjs#102]
Hi,

Thanks for making this available!

Do you have any plans to support [LITERALS](https://github.com/Shopify/liquid/blob/5c5e7de31e6d0da5529b642669343ab4b08afa4f/lib/liquid/context.rb#L135) from the Shopify liquid project?

I use `blank` quite extensively to enable conditional renders of certain sections in a template. It seems to be a foundational part of the Shopify liquid project: https://help.shopify.com/en/themes/liquid/basics/true-and-false#truthy

Something like this:

```
{% unless settings.fp_heading == blank %}
    <h1>{{ settings.fp_heading }}</h1>
{% endunless %}
```

Thanks!

**Comment by scottge** [comment]
I need this feature too. :)

**Comment by harttle** [comment]
Currently I'm shipping Liquid to TypeScript and get it strictly typed, I'll provide this feature ASAP after that.

**Comment by scottge** [comment]
This is amazing. Thank you for the work!!!

Question: I see you add the drop abstract class and interface in this commit too.  Does it mean that for my own custom drops I should start to extend your drop base class?  Would you mind adding a custom drop unit test so that I can follow your example.
