### ISSUE TITLE
Variable content forgotten when getting out of for loop

### ISSUE THREAD

**Issue by rnovacek** [harttle/liquidjs#115]
There's a regression in 7.5.0 (it works fine in 7.4.0). Sometimes (I was not able to find out when precisely) a value of a variable assigned inside a for loop get forgotten when the loop is over.

I've made two fiddles:

This one works (using 7.4.0):
https://jsfiddle.net/9tLvrqm2/

This one does not (using 7.5.0):
https://jsfiddle.net/xharmp0f/

Latest version (8.0.0) behaves the same way as 7.5.0 (it's still broken).

It seems that some variable values are reverted when going out from a for loop.

**Comment by harttle** [comment]
Tags in liquidjs operates the context differently from shopify/liquid, I think we should also introduce Context#environments to simplify the situation.

It should be fixed now, try 8.0.1
