### ISSUE TITLE
Slice filter no longer works (with integers?)

### ISSUE THREAD

**Issue by paulrobertlloyd** [harttle/liquidjs#117]
I was previously able to use the following to generate a series of two-digit month values. This worked by taking a number between 1 and 12, and essentially ‘zeropadding’ numbers between 1 and 9 using the `slice` filter:

```js
{%- for i in (1..12) -%}
  {%- capture month %}{{ i | prepend: '00' | slice: -2, 2 }}{% endcapture -%}
  {{ month }},
{%- endfor -%}
// => 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12,
```

However, the `slice` filter no longer works for this use case, with no transformed number output. I tried converting `i` to a string by using `append: ''`, but that didn’t work. In the end, [I created a separate zero pad filter](https://github.com/paulrobertlloyd/paulrobertlloyd-v4/commit/de697e3e9f41272776feaeca1aa842c21e368958), but this seems unnecessary. I think the change is a result of moving to strictly typed code, but can’t be sure.

**Comment by harttle** [comment]
Try 8.0.3, reopen this issue if it does not work.
