### ISSUE TITLE
Context-aware filters (Feature suggestion/request)

### ISSUE THREAD

**Issue by stephengardner** [harttle/liquidjs#120]
There may be instances where a filter could benefit from being context-aware.  There are also instances of this in the wild within Shopify, such as the `t` (translation) filter.  Within `template/filter/filter.ts` render is passing `this.impl.apply(null, [...])`.  A quick fix would be to pass `ctx` instead of `null` to access the context within a filter render function.  Not saying this is the correct approach, but in any event, perhaps there could be an option to create context-aware filters.

**Comment by harttle** [comment]
Thanks for the request, it's now implemented: https://github.com/harttle/liquidjs/commit/00bc1efe6a514b24b0bfc2e4196ab2211e7d9fa8

**Comment by harttle** [comment]
Try 8.2.0 https://github.com/harttle/liquidjs/commit/87489f60983989f727fef0e9ece734ec9d8fd32c
