### ISSUE TITLE
Does liquidjs do any automatic escaping of HTML?

### ISSUE THREAD

**Issue by waynebloss** [harttle/liquidjs#121]
I am looking for js templating engines that can produce any sort of textual content (including JSON format, JS code and other programming languages).

There don't seem to be any options to disable escaping of HTML output (e.g. turning `<` into `&lt;` and so forth).

So, does liquidjs do any automatic escaping on the outputted text?

**Comment by harttle** [comment]
No, unless applied `escape` filters like `{{foo | escape}}`.

**Comment by waynebloss** [comment]
Thanks!
