### ISSUE TITLE
Immutable reverse filter on arrays

### ISSUE THREAD

**Issue by jeremenichelli** [harttle/liquidjs#126]
Hi there 👋 

This is an issue/question, shouldn't filters be oure functions? Meaning that when they are applied they don't mutate original context data pass to the partial or template.

Here's a reduced case: https://jsfiddle.net/4kq2e6fx/

A collection is assigned to a variable and reversed, twice. This should produce the same outcome (?) but it isn't so it's reversing the original data on every pass.

**Comment by jeremenichelli** [comment]
I saw your release @harttle, does that mean this can be closed?

I wanna first say thank you for how immediate the response to the issue was. I feel bad for not making a PR for it. I actually forked and opened a branch (and went the same way using spread) but couldn't manage to get the test case passing, sorry for that 🙏 

If there's any patreon, collective or anny way I can do a small donation to thank you for your work on this let me know. Thanks again!

**Comment by harttle** [comment]
I'll consider that, thank you :)
