### ISSUE TITLE
for loop using tags data

### ISSUE THREAD

**Issue by nequid** [harttle/liquidjs#127]
Hi, i want to use for loop in tags, so my aim is 
```
engine.registerTag("products", {
  parse: function(tagToken, remainTokens) {
    this.str = tagToken.args; 
  },
  render: function(scope, hash) {
    return [1,2,3,4] // returns sample array data
  }
});
```
and in the view
```
{% for product in products %}
  test loop
{% endfor %}
```
but its not work. data from tag comes in array format but for loop do not work

**Comment by harttle** [comment]
For the view tag `{% for xxx %}`, the tag name is `for`, not `products`. The `products` there is just a variable in current scope. If you want that variable be dynamic, try Drops. For your reference:

* Integration test for Drops: [test/integration/drop/drop.ts](https://github.com/harttle/liquidjs/blob/a606cb5f26c9f580e478577cad2d28f538bde43f/test/integration/drop/drop.ts)
* The origin issue: https://github.com/harttle/liquidjs/issues/97

**Comment by nequid** [comment]
So drops are what i wanted.
