### ISSUE TITLE
Is there any way to pass params to drops

### ISSUE THREAD

**Issue by nequid** [harttle/liquidjs#128]
It would be perfect if we were able to send parameters to drops before we call them
for example
```
{% assign available_products = collection.products(take=12) %}
instead
{% assign available_products = collection.products %}
```
and definition of drop
```
class CustomDrop extends Liquid.Types.Drop {
  async products({ take }) {
    return [{ name: "sample product" }];
  }
}
```

**Comment by harttle** [comment]
I believe not, see https://github.com/Shopify/liquid/issues/29.

`before_method`, which is not supported by liquidjs yet, maybe useful for your case. liquidjs do support `liquidMethodMissing` now and that may help too. If you need that `before_method` feel free to open another  issue specific to it.
