### ISSUE TITLE
User execution

### ISSUE THREAD

**Issue by dv-blk** [harttle/liquidjs#129]
Hello!  

Is this library using measures to protect against malicious user code?  For instance, if a service allowed user uploaded templates in a similar fashion that Shopify allows.  Thanks.

**Comment by harttle** [comment]
In short, yes.

Liquid only support predefined list of operators, filters and tags. So it's not likely to execute arbitrary user code. But like shopify/liquid, all outputs need to be escaped explicitly to avoid xss attack. If you find any security related bugs, feel free to file it here.

**Comment by dv-blk** [comment]
Thanks!
