### ISSUE TITLE
Feature Request: Some missing filters vs Shopify's implementation

### ISSUE THREAD

**Issue by pmalouin** [harttle/liquidjs#132]
Shopify's liquid implementation currently includes some filters that are not supported by this library.

For example, `compact` is used to filter empty elements from an array.
Documentation: https://shopify.github.io/liquid/filters/compact/
Original PR: https://github.com/Shopify/liquid/pull/600

Other missing filters that are documented:
`at_least`: https://shopify.github.io/liquid/filters/at_least/
`at_most`: https://shopify.github.io/liquid/filters/at_most/
`sort_natural`: https://shopify.github.io/liquid/filters/sort_natural/

In the spirit of feature parity, would you consider adding these filters to this library or are there reasons they are excluded?

Thanks!

**Comment by harttle** [comment]
All [standard filters](https://github.com/Shopify/liquid/pull/600/files#diff-844406140a08cdeddd843cfbdf0222d6) are expected to be included in this repo. It'll be appreciated to provide a PR, or later when I have time to get on it.

**Comment by pmalouin** [comment]
@harttle Thanks so much for tackling these improvements in https://github.com/harttle/liquidjs/commit/e6f5f1cd853c8f7fd615937024b5dfeb3da39cf8 ❤️ !

At this point, only the `compact` filter is still missing: https://shopify.github.io/liquid/filters/compact/
