### ISSUE TITLE
Feature request: Synchronous rendering

### ISSUE THREAD

**Issue by Munawwar** [harttle/liquidjs#133]
Hi. Nice work on liquidjs.

Is it possible for parseAndRender() to have an option to synchronously return the output HTML rather than async?

**Comment by Munawwar** [comment]
I'd like my project SahteReact to support liquidjs
https://github.com/Munawwar/SahteReact

**Comment by harttle** [comment]
Duplicate to #48, I'll keep that issue open until we find a solution.
