### ISSUE TITLE
Typescript `target` option value for Node.js

### ISSUE THREAD

**Issue by pmalouin** [harttle/liquidjs#137]
We've been investigating the performance of this library when running on Node.js (server side).

Performance is generally great but while trying to dig deeper in the bottlenecks, we found that the Typescript `target` option value has a big impact on performance. It is currently set to [`es5`](https://github.com/harttle/liquidjs/blob/2ae8c37a4f0fea05916ddbfd3d4c71d1c406d3a6/rollup.config.ts#L32) for published packages (or [`es6`](https://github.com/harttle/liquidjs/blob/2ae8c37a4f0fea05916ddbfd3d4c71d1c406d3a6/tsconfig.json#L3) when running using ts-node). Those `target` values are probably used to maximize compatibility with browsers and older versions of Node.js.

On the other hand, for a Node.js environment where modern ES features are available, we would be able to pick a more modern `target`. I tried to measure the performance gains by picking some higher `target` values, and the biggest perf gain comes when using `es2017`. Here are the benchmarks run with `es6` (current):

```
▶ npm run benchmark

> liquidjs@8.2.4 benchmark /Users/pmalouin/Code2/liquidjs
> ts-node benchmark

--- output ---
literal x 17,752 ops/sec ±11.67% (63 runs sampled)
truncate x 30,953 ops/sec ±10.33% (70 runs sampled)
date x 27,615 ops/sec ±7.72% (67 runs sampled)
escape x 34,631 ops/sec ±5.42% (68 runs sampled)
default x 32,890 ops/sec ±6.30% (71 runs sampled)
--- tag ---
if x 25,857 ops/sec ±5.99% (67 runs sampled)
unless x 27,002 ops/sec ±6.79% (69 runs sampled)
for x 9,931 ops/sec ±6.46% (73 runs sampled)
switch x 12,698 ops/sec ±4.88% (75 runs sampled)
assign x 31,868 ops/sec ±7.49% (67 runs sampled)
capture x 37,483 ops/sec ±5.48% (68 runs sampled)
increment x 55,858 ops/sec ±8.78% (64 runs sampled)
decrement x 50,527 ops/sec ±10.28% (61 runs sampled)
tablerow x 12,473 ops/sec ±9.49% (63 runs sampled)
--- demo ---
demo x 3,865 ops/sec ±17.72% (69 runs sampled)
--- layout ---
cache=false x 2,371 ops/sec ±12.58% (54 runs sampled)
cache=true x 9,968 ops/sec ±11.61% (62 runs sampled)
```

... and here is the same benchmark run with `target` set to `es2017`:
```
▶ npm run benchmark

> liquidjs@8.2.4 benchmark /Users/pmalouin/Code2/liquidjs
> ts-node benchmark

--- output ---
literal x 79,087 ops/sec ±2.35% (77 runs sampled)
truncate x 114,357 ops/sec ±3.64% (72 runs sampled)
date x 64,763 ops/sec ±8.55% (56 runs sampled)
escape x 119,608 ops/sec ±3.47% (69 runs sampled)
default x 127,923 ops/sec ±1.11% (83 runs sampled)
--- tag ---
if x 109,288 ops/sec ±1.59% (81 runs sampled)
unless x 92,181 ops/sec ±2.87% (81 runs sampled)
for x 41,855 ops/sec ±3.19% (80 runs sampled)
switch x 49,737 ops/sec ±3.08% (74 runs sampled)
assign x 141,735 ops/sec ±3.53% (79 runs sampled)
capture x 164,451 ops/sec ±4.51% (75 runs sampled)
increment x 246,954 ops/sec ±6.15% (76 runs sampled)
decrement x 223,379 ops/sec ±4.57% (71 runs sampled)
tablerow x 66,616 ops/sec ±4.81% (72 runs sampled)
--- demo ---
demo x 20,414 ops/sec ±3.05% (73 runs sampled)
--- layout ---
cache=false x 3,699 ops/sec ±15.18% (54 runs sampled)
cache=true x 53,783 ops/sec ±5.04% (71 runs sampled)
```

For some scenarios, we see around 4x improvement without any code change! I suspect this gain has to do with native `async`/`await` support (instead of using a polyfill), but I'm not sure.

We'd be interested in leveraging this better performance in our project. We are wondering what approach would be best to do this.
- Increase the `target` value of this project? What browser support do we need? Can we have a different target only for the Node.js bundle? What versions of Node.js do we need to support?
- Publish an additional bundle in the same package, built with the `es2017` target? We'd need to be able to pick the right bundle when requiring the module (ex. `require('liquidjs/dist/liquidjs.common.es2017')`).
- Publish a different package (ex. `liquidjs-es2017`) that is built using the `es2017` target?

Thanks for your consideration! And let me know if I can help by submitting a PR that fits this project's objectives 🙇

**Comment by harttle** [comment]
Additional `module`, `es2016`, `browser` fields seems better.  It looks like https://github.com/angular/core-builds/blob/dc0c8d828a8bae6591d2b9c77974271481af818c/package.json#L6 , all we need is generate corresonding bundle via rollup. As described [here](http://2ality.com/2017/04/setting-up-multi-platform-packages.html#support-by-bundlers), it's supported by major bundlers like rollup and webpack. If you're using Node.js without a bundler, mayke you need tools like https://www.npmjs.com/package/esm .

**Comment by harttle** [comment]
Another thought is the bundle for Node.js should not contain async/await polyfills any longer, since Node.js 8 is now the lowest [Maintenance LTS](https://nodejs.org/en/about/releases/) version.

So basically I don't think liquidjs should support Node.js without async/await, which is already supprted by Node.js 8: https://node.green/ . I'll set a milestone for shipping to Node.js 8 and providing those additional package.json fields just for convenience.
