### ISSUE TITLE
&& works as an operator in some cases

### ISSUE THREAD

**Issue by robinbijlani** [harttle/liquidjs#144]
It appears that [according to Shopify](https://shopify.github.io/liquid/basics/operators/), the "and" operator should be `and`, and there is no mention of `&&` being supported. This is generally true for liquidjs as well, but there are certain cases where `&&` will work as an operator. For example:
```
{% if obj != null && obj.nested != null %}
```
https://jsfiddle.net/n5op9asL/

This seems inconsistent.

**Comment by robinbijlani** [comment]
I'm finding there are a lot of unexpected results when using unsupported syntax, which seems reasonable. In retrospect, this issue doesn't really seem fair. Closing.

**Comment by harttle** [comment]
That's resonable. But if you find specific error throwing behaviour that's different with shopify/liquid, feel free to open another issue.
