### ISSUE TITLE
type checking for Hash values? 

### ISSUE THREAD

**Issue by mouhannad-sh** [harttle/liquidjs#158]
I have a custom tag 

```liquid
{% tag name_1 | { default:  true } %}
{% tag name_2 | { default: "true" } %}
```

the definition I have is like this 
```js
parse(tagToken) {
      const { default: _default, ...rest } = Hash.parse(tagToken.args);
      this.defaultValue = _default;
	  console.log(_default) 
}
```

current output:
```
'true' 
'"true"'
```
expected 
```
true // as boolean
"true" // as string
```

Am I doing something wrong? is there a better way to do this ?

**Comment by harttle** [comment]
Try `Hash.create` or `Hash.createSync`, what they do is parse and evaluate each expression. See: https://harttle.land/liquidjs/classes/_template_tag_hash_.hash.html

**Comment by mouhannad-sh** [comment]
it seems to be exactly what I needed 🎉 

I changed it to the following 

```javascript
async parse(tagToken, context) {
      const { default: _default, ...rest } = await Hash.create(tagToken.args, context);
      this.defaultValue = _default;
      console.log(_default, { type: typeof _default }); 
}
```

Input

```
{% tag name_1 | { default: true } %}
{% var name_2 | { default: "true" } %}
{% var name_3 | { default: '"true"' } %}
```

Output 🔥 

```
true { type: 'boolean' }
true { type: 'string' }
"true" { type: 'string' }
```

many thanks !

**Comment by mouhannad-sh** [comment]
@harttle it seems like `Hash.create` doesn't work anymore on the latest version (9.14.1) was working on `9.0.0` 

is it possible to achieve the same thing using the new API ?

thanks

**Comment by harttle** [comment]
It's still there but a bit different, I exported a `toPromise` (see the above commit) the for ease of use.

```javascript
const { Context, Hash, toPromise } = require('liquidjs')

const hash = new Hash('foo:bar')
const ctx = new Context({bar: 'BAR'})

// Outputs:
// { foo: 'BAR' }
toPromise(hash.render(ctx)).then(console.log)
// or `toValue` to render syncly
```
