### ISSUE TITLE
Better Reference/Guidance on [making plugins] for Filters Not Included in Shopify's Spec for Liquid

### ISSUE THREAD

**Issue by wturnerharris** [harttle/liquidjs#159]
Hello @harttle ,

Thanks for this project and congrats on v9 release. 

I'm writing to see if there's guidance on working with custom tags and filters, especially those that are included by Shopify yet excluded from Shopify's spec for the liquid templating engine. The [`handleize`](https://help.shopify.com/en/themes/liquid/filters/string-filters#handle-handleize) filter is an example. I see some [issues](https://github.com/harttle/liquidjs/pull/139) related to this where the recommendation is to create a plugin. The wiki provides [this guidance](https://github.com/harttle/liquidjs/wiki/Write-a-Plugin), but it feels rather sparse. Namely, looking for best practices for writing a plugin, guidance on TS best practices for the project, and any existing plugins already in the wild would be appreciated. 

Additionally, I found a couple ([`section`](https://github.com/harttle/liquidjs-section-tags) tag, color filters) that you wrote. We ended up writing the same ones—section, schema, javascript, stylesheet— as we could not find the plugin list. We've been writing these for our own internal projects, but it feels like it needs a bit more structure. Additionally, we typically write these in vanilla JS whereas this repo uses TS, but that's not a negative or positive, it just deviates from the style of the project.

Thus, I think that this project would benefit from the following:
1. Greater clarity on writing plugins and their requirements, specifically if one should follow TS for convention-purposes.
2. A list of plugins, specifically for those who are emulating some Shopify-proper scenarios.
2. Some wiki cleanup, to better direct plugin creation as well as to help others looking for Shopify tags/filters.

Do you know of any plugins contributed that support a variety of Shopify-platform-based tags and filters? Already found yours, but I noticed that the wiki points to a list, but really just points back to the project's github page.

![Screen Shot 2019-09-23 at 3 17 21 PM](https://user-images.githubusercontent.com/887488/65455732-d1f9cf80-de15-11e9-9f90-f691057ee536.png)

Happy to help update wiki once guidance and preference has been dictated here. I was thinking of making a liquidjs-shopify-plugins repo for this, or even adding to your existing liquid-section-tags repo, or further more, make a wrapper of several plugins that will, again, allow those using liquidjs to better emulate the Shopify platform (and not just the spec for liquid).

Looking forward to hearing your thoughts so that we can contribute.

**Comment by harttle** [comment]
Great to hear from you, your advices and that you're willing to contribute on the plugins! Firstly here're answers to some of the above questions:

1. Requirements and guidance for writing plugins. 
    * I suppose there should be little requirements except that it should be able to be used by `engine.plugin(<pluginInstance>)`. 
    * People may not care much about the types for plugins since plugins are not meant to be called by JavaScript, so I think vanilla JS is OK. 
    * As for the guidance, I was planning to add more tutorials when the APIs are stable. Feel free to add some tutorial contents or outlines and I'll help to review and populate more contents.
2. Plugin list. Currrently plugins are mostly private and not yet widely used. There's
a list of plugins in the README.md and it's not formal, I agree it should be moved into the wiki page and give better guidance.

![image](https://user-images.githubusercontent.com/4427974/65481035-70456e00-dec6-11e9-8d16-236e30b7904c.png)

3. liquidjs-shopify-plugins. It's a great idea and I'm willing to move those two plugins into yours. Those plugins are create by myself in response to some issues. But I'm not familiar with shopify and honestly I even don't have a shopify account. So I believe you can do better than me.

Now I removed that "editing to collaborators only" restriction for the wiki page. Feel free to make changes and open discussions for specific problems.

**Comment by wturnerharris** [comment]
@harttle - thanks for the feedback and guidance. 

1. I will go ahead and clean up some of the wiki (if not just for myself), and let you guide whether the changes are acceptable.
2. I will create the aforementioned repo for `liquidjs-shopify-plugins` and see if I can find any others in the wild. I think it will help those who do want to use liquidjs as a testing pattern for Shopify websites. We do a lot of that, so I think we'll find active contribution and be able to direct those coming to the liquidjs project page and missing those features.

I'm going to close this issue and start the above!
