### ISSUE TITLE
Support for the "render" tag

### ISSUE THREAD

**Issue by tylersticka** [harttle/liquidjs#163]
(Apologies if this issue is a duplicate, the keyword `render` is a troublesome one to search a repository for!)

Shopify recently added the `{% include %}` tag to its list of deprecated tags, in favor of the newly added `{% render %}` tag (Shopify/liquid#1122). [To quote their docs](https://help.shopify.com/en/themes/liquid/tags/deprecated-tags):

> The `include` tag works similarly to the [`render`](https://help.shopify.com/en/themes/liquid/tags/theme-tags#render) tag, but it lets the code inside of the snippet to access and overwrite the variables within its parent template. The `include` tag has been deprecated because the way that it handles variables reduces performance and makes theme code harder to both read and maintain.

We work on a few projects with Shopify integrations, and developers have been pretty gung-ho about the new tag because its variable inheritance is a bit more predictable and because Shopify doesn't deprecate tags very often.

**Comment by harttle** [comment]
Thank you for you informative description :) It's now published in v9.2.0 and if there's any problem feel free to file a specific issue.  Closing this one.
