### ISSUE TITLE
Support for Node.js file resolve based on require.resolve

### ISSUE THREAD

**Issue by rdmurphy** [harttle/liquidjs#168]
Hello! 👋 

I was wondering if you'd consider support (either via a flag, or something else!) for allowing file resolution on the Node.js side to be optionally based on [`require.resolve`](https://nodejs.org/api/modules.html#modules_require_resolve_request_options). What this would enable is the ability to provide paths to the `{% layout %}` and `{% include %}` tags that are able to find templates that may have been installed via `npm`. What's kind of cool about that is that you can maintain a separate project just for templates and such that could easily be imported into a project. [Earlier this year Nunjucks added similar functionality](https://github.com/mozilla/nunjucks/blob/master/nunjucks/src/node-loaders.js#L128).

I do think this could be accomplished easily enough by providing a custom `fs` implementation, but it's unfortunate that a user would be required to essentially copy all of the existing [Node implementation](https://github.com/harttle/liquidjs/blob/master/src/fs/node.ts) only to alter the `resolve` function.

If there are any other easier paths I may be overlooking, please let me know! I've been using Nunjucks for a while but increasingly keep coming back to Liquid JS and this is one of the few features I'd miss out on.

Thank you!

**Comment by harttle** [comment]
It seems the [root](https://harttle.land/liquidjs/interfaces/_liquid_options_.liquidoptions.html#root) option is not enough to cover this situation. Maybe we need another option for this, or it can be implemented as a fallback when no templates found in root directories, in which case it'll be backward-compatible and the additional option is not needed.

Another concern is `require` is not provided by browsers, so the implementation should go into [fs/node.ts](https://github.com/harttle/liquidjs/blob/master/src/fs/node.ts) and be checked in [parseFile](https://github.com/harttle/liquidjs/blob/master/src/liquid.ts#L67) when trying to call it.

Feel free to file a PR if you're already digging into it, I can help with the test cases and doc.

**Comment by harttle** [comment]
Not it's implemented as a fallback so if no templates found under `root` directories, `require.resolve` will apply.

**Comment by rdmurphy** [comment]
Awesome, thank you! 🙌 

Sorry I didn't respond earlier — got suddenly swamped this week. I think it was a good call to do it *after* an attempted local search too! That was going to be my main suggestion.
