### ISSUE TITLE
Whitespace control

### ISSUE THREAD

**Issue by ilg-ul** [harttle/liquidjs#17]
Could you consider adding white space control, as in the original shopify implementation?

https://shopify.github.io/liquid/basics/whitespace/

That would greatly improve templates readability.

Thank you,

Liviu

**Comment by harttle** [comment]
You're right, it's a useful feature. I'll try to implement it this month.

**Comment by ilg-ul** [comment]
For comparison, here is how Jinja processes white spaces:

http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

To be noted the use of global flags to control the behaviour of all tags. I don't know if the original Liquid specs uses such global flags, but they are useful.

FYI, I successfully used your template engine in my project:

https://github.com/xcdl/xcdl-js/tree/master/assets/templates

The only small annoyance is the presence of some long lines, which I cannot split, because I get empty lines in the generated files. But this will hopefully be gone when you'll add white space control.

**Comment by harttle** [comment]
I believe the global flags are more useful since almost all tags are not meant to be displayed as a blank line. And `{%+` syntax (which comes along with `{%-`) should be necessary to allow intentional white spaces.

Useful as it is, this behavior should be disabled by default for backward compatibility. I'll give a document later.

**Comment by ilg-ul** [comment]
please be sure you follow the liquid/ruby functionality, the link I gave you before is for jinja, which is the python equivalent, so the specs might not be fully compatible.

**Comment by ilg-ul** [comment]
could you add some explanations on how to use the new features in the README file?

**Comment by harttle** [comment]
See [this][options] for the construction `options`, and [this][wc] for the explanations.

[options]: https://github.com/harttle/shopify-liquid#options
[wc]: https://github.com/harttle/shopify-liquid/wiki/Whitespace-Control

**Comment by ilg-ul** [comment]
Thank you, I'll give it a try during the next days.

**Comment by ilg-ul** [comment]
defining `trim_right` was ok for my templates (https://github.com/xcdl/xcdl-js/tree/master/assets/templates).

`trim_left` triggered some errors, it might _eat_ too much. anyway, in my case, it is not needed, `trim_right` seems enough.

**Comment by harttle** [comment]
The behavior of `trim_left` is identical to `{%-`, which trims all blank characters (including `\n`) from the left. The `{%-` behaves the same with the Ruby version.

**Comment by ilg-ul** [comment]
The behaviour might be identical, but enabling it in my use case triggers an error:

```
ParseError: undefined filter: register, file:/Users/ilg/My Files/MacBookPro Projects/XCDL/xcdl-js.git/assets/templates/qemu-peripherals-h.liquid, line:82
```

Line 82 is the second line of the define:
```
#define {{ vendorPrefix }}_{{ periphName }}_STATE(obj) \
    OBJECT_CHECK({{ vendorPrefix }}{{ periphName }}State, (obj), TYPE_{{ vendorPrefix }}_{{ periphName }})
```

You might still have a bug somewhere in your code.

And I'm not sure `trim_left` should remove a trailing `\n` from the previous line.

**Comment by ilg-ul** [comment]
I have some templates that must be as portable as possible, and I got bitten again by a whitespace issue.

the short story is that `trim_right` is unusable in real cases, since it also affects `{{ ... }}` and common sequences of subtitutions that require to be separated by spaces (like `{{ one }} {{ two }} {{ three }}`), are rendered as a concatenat string, which is not acceptable.

using `{{ one +}} {{ two }}` is not possible, since the other platforms do not support this extension.

so I had to remove `trim_right` and use an explicit `-%}` in all instances, which is not very nice...

**Comment by harttle** [comment]
As far as I know, [whitespace control in shopify/liquid](https://shopify.github.io/liquid/basics/whitespace/) also deals with `{{` and `}}`. I'm not sure what mistake I made.
Since you're heavily relying on whitespace control, I'll appreciate it if you can PR some test cases, or more specified-document. I'll be happy to implement.

**Comment by ilg-ul** [comment]
yes, the shopify documentation is not very clear how whitespace control should behave. it is clear that `{{- ... -}}` and `{%- ... -%}` should strip whitespaces from left/right, but it does not define how far stripping should go and also does not define the behaviour of global `trim_left/trim_right` switches.

after using _liquid_ templates in JS and Java, and having serious problems with preserving empty lines and spacing between substituted variables, my conclusions are:

- striping should not go past the first line terminator; in other words, stripping should 'eat' as many spaces and tabs, but at most one `\n`; if more spaces or line terminators follow, they should be preserved; going past the first line terminator makes entering empty lines impossible.

- global switches, like `trim_left/trim_right`, aparently are useful, but their behaviour is wildly non-portable; if implemented, they should also not go past the first line terminator, and **should not** apply to both `{{- ... -}}` and `{%- ... -%}` indiscrimently; either they should apply only to `{%- ... -%}`, or different switches should be used for `{{- ... -}}` and for `{%- ... -%}`.

when I'll have my templates fully functional on JS and Java, I'll try to help you with some test cases.

**Comment by harttle** [comment]
It's reasonable to provide different switches for `{{- ... -}}` and for `{%- ... -%}`. As for the "should not go past the first line terminator", I'll dig into the ruby version to find the exact implementation.

**Comment by harttle** [comment]
I brought some [test cases from shopify/liquid](https://github.com/harttle/liquidjs/blob/master/test/whitespace-control.js), but they seems to be trimming more than one `\n`s.

Anyway, liquidjs now provides [`greedy` option](https://github.com/harttle/liquidjs#options) to restrict trimming only one `\n`. In the meantime, there're `trim_tag_right`, `trim_tag_left`, `trim_value_right`, and `trim_value_left` available.

> Try the latest `master` branch. Note: these options are not backward-compatible, so they'll be published in next major version.

**Comment by harttle** [comment]
We have tried our best to make things easier and keep compatible to shopify/liquid at the same time. Any idear or PR are welcome. Closing now.
