### ISSUE TITLE
npm package doesn't contain esm module for browser

### ISSUE THREAD

**Issue by a-gerescher** [harttle/liquidjs#173]
I am building an angular component for liquidjs. Therefore i want to include your lib, in the browser (no fs namespace available) and want to be able to treeshake with a bundler. Conditional imports are problematic in this case.

```
./node_modules/liquidjs/dist/liquid.esm.js 411:19-40 Critical dependency: the request of a dependency is an expression
Module not found: Error: Can't resolve 'fs' in '/node_modules/liquidjs/dist'
Module not found: Error: Can't resolve 'path' in '/node_modules/liquidjs/dist'
```

**Comment by harttle** [comment]
Now `liquid.esm.js` is targeted to browsers so there could be a degradation if someone is using `liquid.esm.js` on Node.js. But I believe the esm version is only useful for bundles, which is in most case targeting browsers, hope it makes sense.

**Comment by a-gerescher** [comment]
Thank you so much! :-)
