### ISSUE TITLE
Access closing Liquid tag

### ISSUE THREAD

**Issue by davidwarrington** [harttle/liquidjs#174]
I'd like to use this as a parser for a Liquid beautifier. Unfortunately the parser doesn't seem to give me access to the closing tags for if statements, for example. Am I missing something, or will I have to make use of the raw input to extract the closing tag?

**Comment by harttle** [comment]
Parsers for specific tags are implemented by `src/builtin/tags/<tagName>`. The [Liquid#parse](https://harttle.land/liquidjs/classes/_liquid_.liquid.html#parse) makes use of those implementations and generates a list of parsed tags/outputs/htmls, which I believe gives you enough information.

**Comment by davidwarrington** [comment]
I might have missed something, but I don't see anything in the parsed data that tells me about the `{% endif %}` tag, for example. How does the parser determine whitespace control on the `{% endif %}` tag? Unless I'm mistaken, `token.trimLeft` and `token.trimRight` only refer to the opening `{% if %}` tag.

I'll have another look later, but this is where I'm up to.

**Comment by harttle** [comment]
I guess I know what you're saying. The returned templates by `.parse()` will be used by `.render()` only, to be more specific, the `for` Tag instance will only be used by the `render()` defined inside `src/builtin/tags/for.ts`. The `endif` tag is not used during render so for.ts decides not to save it, see [src/builtin/tags/for.ts#L31](https://github.com/harttle/liquidjs/blob/ef289039fbdd9bd3c1329020d086ac92a6d35286/src/builtin/tags/for.ts#L31l). 

The first token `{%for%}` of the for block triggers the parsing of For tag but Liquid don't care how many subsequent tokens `For#parse()` consumes, though it's can be counted (keep track of the length of the tokens before and after calling `For#parse()` in `src/temlate/tag/tag.ts`. If that's what you want, make a PR to save those tokens on the Tag, or just file another more specific issue.

If you just cares about the trimming, which is treated during tokenization, which is done before actually parsing, the folloing snippet will be a starting point:

```javascript
(new Liquid()).tokenizer.tokenize('{%if false%}a{%endif%}')
```

**Comment by davidwarrington** [comment]
Currently trimming is the only concern. `.tokenizer.tokenize` works great, thank you.
