### ISSUE TITLE
Does liquidjs supports translation keys and t filter?

### ISSUE THREAD

**Issue by olsi-qose** [harttle/liquidjs#176]
Hi! Could not find the `t` filter in the builtin filters wiki page (https://github.com/harttle/liquidjs/wiki/Builtin-Filters) .
Does liquidjs support translation keys for multi-language implementations? 
If so, is it possible to have an example?

**Comment by harttle** [comment]
AFAIK, the T filter is not a standard filter (which is provided by shopify/liquid) thus we'll not implement it until it's included in that official repo. Also see #159 for more information about the status of T filter and 3rd party plugins.

**Comment by wturnerharris** [comment]
@olsi-qose - if it helps, I started a repo of [liquidjs plugins for Shopify](https://github.com/wturnerharris/liquidjs-shopify-plugins). It is very early and needs some testing love, but it's what we're using for a few of the filters that are Shopify-specific. Will be adding some tags soon, but most of those are usable from https://github.com/harttle/liquidjs-section-tags

**Comment by harttle** [comment]
I can transfer the liquidjs-section-tags repo to you, or just delete it after its code merged into your liquidjs-shopify-plugins. If it's ready feel free to ping me, I can help to update the plugin list.

**Comment by wturnerharris** [comment]
@harttle sure, I think migrating the existing one into a single repo would be fine. Once that's complete, I can ping you to delete and update the plugins list.

**Comment by wturnerharris** [comment]
@harttle - saw that you closed this out, and that reminded me that I created [this](https://github.com/wturnerharris/liquidjs-shopify-plugins) a few months ago, but I got pulled away to other projects.

I've got a few other updates I need to add due to liquidjs API updates recently as well as some tags and tests for both.
