### ISSUE TITLE
Support for flags in "date" filter formatting

### ISSUE THREAD

**Issue by caramiki** [harttle/liquidjs#177]
liquidjs doesn't seem to support flags when formatting time.

For example, this works:

```
{{ some_date | date: "%Y/%m/%d" }}
```

But using the `-` flag to remove padding does not work:

```
{{ some_date | date: "%Y/%-m/%-d" }}
```

Ruby Liquid uses [strftime](https://apidock.com/ruby/DateTime/strftime) which uses flags, and my expectation was that liquidjs would work the same way.

**Comment by harttle** [comment]
Thanks for the reference. strftime is implemented inside liquidjs and there maybe many differences but I'll fix them once on need. For your case, I'm planning to implement these flags along with the `%<flags><width><modifier><conversion>` directive syntax:

* `-`  don't pad a numerical output.
* `_`  use spaces for padding.
* `0`  use zeros for padding.
* `^`  upcase the result string.
* `#`  change case.
* `:`  use colons for %z.
