### ISSUE TITLE
Where nested property is not supported

### ISSUE THREAD

**Issue by maharrabi** [harttle/liquidjs#178]
The where filter as sort & map for ex, dont support nested property filter 
ex: {% assign variable = authors | where: 'books.year', 2019 %}

**Comment by harttle** [comment]
Supported on @9.5.0
You can find a test case here: https://github.com/harttle/liquidjs/commit/60ec74f55d83994f3db6df1f9530e36af0f94d74#diff-513ba559a0340b55020e8432e057659aR172-R188
