### ISSUE TITLE
Define global objects which can be accessed by render tag 

### ISSUE THREAD

**Issue by paulrobertlloyd** [harttle/liquidjs#185]
Having experienced a few cases where variables have unintentionally leaked into included template partials, it was interested to note that Liquid (and LiquidJS) now support the stricter `render` tag, and that `include` has been deprecated.

I tried to update my [11ty](https://www.11ty.dev)-generated site to use `render`, but in doing so, soon came across a limitation; global data objects are not available to rendered partials.

For example, I have the following partial:

```liquid
<header class="banner">
  <div class="banner__container">
    <div class="banner__title">
      <a rel="home" href="/">{{ app.title }}</a>
    </div>
    <nav class="banner__navigation" aria-label="site">
      {%- render 'navigation' with navigation.primary -%}
      {%- render 'navigation' with navigation.secondary -%}
    </nav>
  </div>
</header>
```

The data for both `app` and `navigation` comes from [global data files](https://www.11ty.dev/docs/data-global/). Given the encapsulated nature of `render`, I have to declare these each time I wish to render this partial on a page, which is not always easy or possible within the confines of a Liquid template.

Looking at the [relevant Shopify theme docs](https://help.shopify.com/en/themes/liquid/tags/theme-tags#render), I note that:

> [Global objects](https://help.shopify.com/en/themes/liquid/objects#global-objects) don't need to be passed down. They are accessible from all files.

Shopify define their own global objects, but there’s no way for an author using LiquidJS to do the same, as far as I can see.

I imagine being able to define an array of `globals` when configuring LiquidJS (shown within the context of an 11ty configuration), like so:

```js
const {Liquid} = require('liquidjs');
const app = require('./src/_data/app.json');
const navigation = require('./src/_data/navigation.json');

module.exports = function(eleventyConfig) {
  let options = {
    extname: '.liquid',
    strict_filters: true,
    root: [
      './src/_includes',
      './src/_layouts'
    ],
    globals: [
      app,
      navigation
    ]
  };

  eleventyConfig.setLibrary('liquid', new Liquid(options));
};
```

Alternatively, perhaps an object would allow authors to define a name for each global:

```js
globals: {
  foo: app,
  bar: navigation
}
```

Not sure which is the best approach; I have no preference.

Is this a legitimate feature request, or have I missed something?

**Comment by harttle** [comment]
At first glance it seems something contradictory: we need to make the variables passed down explicit, and we need globals at the same time. But I'll try to be compatible with the shopify liquid and dig into that behaviour to make sure it's intended. And I prefer to the second way (in which you can define a object literal to specify the globals).

**Comment by harttle** [comment]
Try liquidjs@9.7.0, it should be supported by passing [globals](https://harttle.land/liquidjs/interfaces/_liquid_options_.liquidoptions.html#globals) option.

**Comment by paulrobertlloyd** [comment]
Thanks @harttle; started working with this, and all seems to work as expected. Will file any bugs/issues if I come across them. Thanks so much for adding this feature so quickly!

**Comment by zeroedin** [comment]
@harttle is there a way to get globals option to work with Express Liquid integration?  https://liquidjs.com/tutorials/use-in-expressjs.html  

I feel like i'm going down a rabbit hole here, I understand the express `res.render` method does not take the same params as the `liquid.renderFile` method, so trying to work my way around that.  Any ideas? Maybe I am I overlooking something but I think i'm at the point where using `res.render` is out of the question for Liquid global variables.

**Comment by zeroedin** [comment]
I think I might have found a solution:

```
  let engine = new Liquid({
    root: path.join(__dirname, 'views'),
    extname: '.liquid'  // used for layouts/includes, defaults ""
  })
  app.engine('liquid', engine.express({}))

  app.set('views', path.join(__dirname, 'views'))
  app.set('view engine', 'liquid')
  
  let html = engine.renderFileSync(path.join(__dirname, 'views','index'), {
    data: 'local'
  }, {
    globals: { data: 'global' }
  })

  res.send(html)
```

To use in an express router I had to set `app.local.engine = engine` in a app.js middleware and use `app.locals.engine.renderFileSync`

**Comment by harttle** [comment]
The `globals` can be set when creating an`engine` object.

```
let engine = new Liquid({
    root: path.join(__dirname, 'views'),
    extname: '.liquid'  // used for layouts/includes, defaults "",
    globals: {data: 'global'}
  })
```

**Comment by cyberwombat** [comment]
@harttle currently it seems in 9.28.5 at least, globals are not available to the inner templates added through `render`.  Was this fixed in master?

**Comment by harttle** [comment]
I don't know that. Will check it out and fix soon if that's a problem.

**Comment by AsadCSE** [comment]
Hello, firstly i'm new to templating, I was wondering if dynamic handles could be passed to fetch objects asynchronously from database before rendering. Like in the example: 

`{% assign featured_product = all_products['product_handle'] %}`

if 'all_products' be global asynchronous function which fetches 'product_handle' and passes the data for parsing and rendering, how to do that? can you help?

**Comment by jsuiker** [comment]
the settings object indeed does not work when using express res.render method

**Comment by jsuiker** [comment]
@harttle please see the following repo for a minimal example of the settings object NOT working when using express res.render()

https://github.com/jsuiker/liquidjs-express-globals

**Comment by harttle** [comment]
I find expressjs passed a local `settings` variable when calling render engines. Sadly I don't find any docs from its website. But if you delete that from `locals`, your demo will work fine:

```javascript
  var app = express()
  // after `express` is created, delete its `.locals.settings`:
  delete app.locals.settings;
```
