### ISSUE TITLE
[Regression v9] Comparison operator with no space after first operand is always false

### ISSUE THREAD

**Issue by slavivanov** [harttle/liquidjs#186]
Hi, and first of all thank you for the awesome Liquid implementation. 

We recently upgraded a to latest version 9 and discovered the following regression (the following worked up to 8.5.3):
`{% if true==true %}success{%else%}fail{% endif %}` outputs "fail".
The same thing happens when using a variable:
`{% assign var = 1 %}
{% if var==1 %}success{%else%}fail{% endif %}` outputs "fail".

If there is a space after the first operand, the comparison works:
`{% if true ==true %}success{%else%}fail{% endif %}` outputs "success".

Same repro case in Runkit: https://runkit.com/slavivanov/5e3c7cd5be5ed70017e8a265

**Comment by harttle** [comment]
Try liquidjs@9.7.0, it should be fixed.

**Comment by slavivanov** [comment]
You are too cool, thanks!
