### ISSUE TITLE
Access built-in filters?

### ISSUE THREAD

**Issue by pdehaan** [harttle/liquidjs#188]
Is there a way to access the built-in liquidjs filters from a liquidjs class/instance?

I'm using eleventy, and wanted to try sharing filters between liquidjs and nunjucks.

I tried the following, but didn't see any references to filters and am not sure I understand where the filters are stored internally, or if they're private:

```js
const util = require("util");

const liquid = require("liquidjs");

console.log(util.inspect(liquid));
console.log(util.inspect(new liquid()));
```

**Comment by harttle** [comment]
Currently, filters are registered to the `impl` static property of `Filter` class([src/template/filter/filter.ts](https://github.com/harttle/liquidjs/blob/66541a62fde5edb60866b88982e4e529498a7399/src/template/filter/filter.ts#L13)), which is referenced as a closure variable by `Liquid`.

Thanks to this issue I find out that during every `Liquid` construction builtin tags/filters are re-registered, and each liquid instance always has the same set of tags/filters despite of the fact that `.registerFilter()` and `.registerTag()` are instance methods.

Definitely we should make the set of filters and tags properties of `Liquid`, are you interested to make a PR? I can help for the test cases.
