### ISSUE TITLE
Add json filter for debugging objects?

### ISSUE THREAD

**Issue by pdehaan** [harttle/liquidjs#192]
In Nunjucks there is a `dump(n)` filter which is basically `JSON.stringify(obj, null, n)` (if I understand correctly).

I'm struggling to find something similar w/ Liquid.
Closest I've found is https://github.com/Shopify/liquid/issues/121 (and a couple other references to a `json`) filter, but I cannot seem to get that to work w/ liquidjs. 

```js
const { Liquid } = require('liquidjs');
const engine = new Liquid();

engine
    .parseAndRender('{{ name | json }}', {name: {first:'alice', last: 'poppins'}})
    .then(console.log);     // outputs '[object Object]'

const pkg = require("liquidjs/package.json");
console.log(`${pkg.name} @ v${pkg.version}`); // liquidjs @ v9.7.0
```

**UPDATE:** Ah, OK, so if I enable the Boolean `strictFilters` option, I get a hard error saying:

> _ParseError: undefined filter: json, line:1, col:1_

**Comment by pdehaan** [comment]
Workaround:
```js
engine.registerFilter('json', (v, n=0) => JSON.stringify(v, null, n));
```

**Comment by harttle** [comment]
maybe better to use `util.inspect()`, I'll see how it's done in shopify/liquid

**Comment by harttle** [comment]
A `json` filter is builtin from 9.10.0 on, see:  https://github.com/harttle/liquidjs/blob/607a5cda3f049cc2cec17f77f9ba29706e8e46bf/src/builtin/filters/object.ts#L8-L10
