### ISSUE TITLE
Global data feature does not parse data files that export a function

### ISSUE THREAD

**Issue by paulrobertlloyd** [harttle/liquidjs#194]
First, some background. I’m using 11ty, and have LiquidJS setup to use the following globals:

```js
const parser = new Liquid({
    cache: true,
    dynamicPartials: true,
    globals: {
      app: require('../path/to/app'),
      dates: require('../path/to/dates'),
      venues: require('../path/to/venues')
    }
  });
};
```

`app` requires `app.js` which exports an object. This works as expected:

```js
module.exports = {
  foo: 'bar',
}
```

`dates` requires `dates.json` which is a JSON file. This also works as expected.

However, `venues` requires `venues.js`, which exports a function which returns an object (structuring the data in a format 11ty expects):

```js
module.exports = function () {
  const venues = [{
    title: '68 Middle Street',
    address: {
      locality: 'Brighton',
      region: 'Sussex',
      'country-name': 'United Kingdom',
      'postal-code': 'BN1 1AL',
      'plus-code': '9C2XRVC4+CQ'
    }
  }, { … }];

  return venues.map(venue => {
    const fileSlug = venue.address['plus-code'].toLowerCase();

    return {
      date: new Date(),
      fileSlug,
      url: `/events/venues/${fileSlug}`,
      data: {
        layout: 'venue',
        title: venue.title,
        address: venue.address,
      }
    };
  });
};
```

However, when I inspect the returned data in my templates, instead of seeing `[object Object]` or similar, I see that the function is being returned instead:

`function () { const venues = [{ title: '68 Middle Street', address: { locality: 'Brighton', region: 'Sussex', 'country-name': 'United Kingdom', 'postal-code': 'BN1 1AL', 'plus-code': '9C2XRVC4+CQ' } }, { … }`

If I call this data file outside of Liquid globals (i.e. by using 11ty’s global data feature), it works as expected.

Is there something I’m doing wrong here, or should LiquidJS globals account for this scenario, where a data file exports a function?

**Comment by harttle** [comment]
If I'm not mistaken, I believe that function should be called before passed to `globals`, like: 

```javascript
const parser = new Liquid({
    cache: true,
    dynamicPartials: true,
    globals: {
      app: require('../path/to/app'),
      dates: require('../path/to/dates'),
      venues: require('../path/to/venues')()
    }
  });
};
```

Note the `()` after requiring venues.js

**Comment by paulrobertlloyd** [comment]
🤦🏼‍♂️ Urgh, of course. Thanks!
