### ISSUE TITLE
Does the render tag support with/as and for/as?

### ISSUE THREAD

**Issue by paulrobertlloyd** [harttle/liquidjs#195]
Reviewing [documentation for the `render` tag](https://shopify.dev/docs/liquid/reference/tags/theme-tags#render), it appears to have a few parameters that are not supported by LiquidJS.

## The `with` parameter

> A single object can be passed to a snippet by using the `with` and `as` parameters:
>
> ```nunjucks
> {% assign featured_product = all_products['product_handle'] %}
> {% render 'product' with featured_product as product %}
> ```
>
> In the example above, the `product` variable in the snippet will hold the value of `featured_product` in the parent template.

In my testing, it appears that while LiquidJS supports `with`, it does not support reassignment using `as`.

## The `for` parameter
> A snippet can be rendered once for each value of an enumerable object by using the `for` and `as` parameters:
>
> ```nunjucks
> {% assign variants = product.variants %}
> {% render 'variant' for variants as variant %}
> ```
>
> In the example above, the snippet will be rendered once for each variant of the product, and the variant variable will hold a product `variant` object within the snippet.
>
> When using the `for` parameter, the [`forloop` object](https://shopify.dev/docs/liquid/reference/objects/for-loops) is accessible within the snippet.

In my testing, it appears that LiquidJS does not support the `for` and `as` parameters.

Looking at the code for `render` in [`shopify/liquid`](https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/render.rb), it appears these are core Liquid features (i.e., they are not Shopify specific), but I could be wrong.

What is the status of these parameters?

**Comment by harttle** [comment]
Some tags do support `with` attribute, I'll check it for the `render` tag. The `for` attribute for the `render` tag is not supported now but it should be.

**Comment by paulrobertlloyd** [comment]
Does `as` qualify for support in LiquidJS too?

**Comment by harttle** [comment]
Yes, I see it implemented in shopify/liquid.

**Comment by harttle** [comment]
Some use cases:

https://github.com/harttle/liquidjs/blob/607a5cda3f049cc2cec17f77f9ba29706e8e46bf/test/integration/builtin/tags/render.ts#L99-L131

**Comment by paulrobertlloyd** [comment]
Awesome, thanks @harttle – can’t wait to try this out! 🎉
