### ISSUE TITLE
how to access custom tags attributes if the tag returns object

### ISSUE THREAD

**Issue by Ali-Dalal** [harttle/liquidjs#199]
in case we have the following custom tag
```javascript
engine.registerTag('person', {
    render: async function () {
        return {
            name: 'John',
            lastname:'doh'
        };
    }
});
```
accessing the name of the person returns [object object]

```javascript
const koko2 = `<h1>{% person.name %}</h1>`;
//output:  <h1>[object Object]</h1>
```

What is the right way to do it?

**Comment by harttle** [comment]
The `render` method is expected to return a string to output, in your case `{ name: 'Join', lastname: 'doh' }` is converted to string which is `"[object Object]"`.

Inside `{% person.name %}`, the string `person` is parsed by LiquidJS to find the tag you registered, and `.name` is passed to the `parse()` method which is not defined in your registration. A running example would be:

```javascript
const engine = new Liquid()

engine.registerTag('person', {
  parse: function (token) {
    this.property = token.args.trim()
  },
  render: async function () {
    return ({
      name: 'John',
      lastname: 'doh'
    })[this.property]
  }
})
const html = await engine.parseAndRender(`<h1>{% person name %}</h1>`)
// html === '<h1>John</h1>'
```

**Comment by Ali-Dalal** [comment]
@harttle Thanks for the help.

in case the tag is fetching an API, every time the tag is called it will fetch the data again and again? am I right?

my case is we need to define custom tags that fetch some numbers and stats. the reason why I am not sending the data to the engine as params is I have might have multiple liquid in database and each one might contain different data. thus I want to lazy load the only required data and not fetching everything and pass it to the liquid engine.

any recommendation?

**Comment by harttle** [comment]
> in case the tag is fetching an API, every time the tag is called it will fetch the data again and again? am I right?

It's up to your tag implementation. Save the fetched data into a global/closure variable and skip fetch the next time, or introduce a resource management object to handle fetching, caching and concurrency.

> any recommendation?

It's better to fetch all the data needed before calling `.render()`, as long as all the data needed to determine which database to request is available.

**Comment by Ali-Dalal** [comment]
@harttle Thanks for the help

is it right to inject data to context.scopes during the runtime?

example, let's define a custom tag:
```js
function registerTags() {
    engine.registerTag('custom_tag', {
        parse: (token) => {
            this.options = JSON.parse(token.args.trim());
        },
        render: async (context) => {
            let result = 'do something here maybe API call with the options';
            context.scopes.push({ result: result });
        }
    })
}
//call the tag:
<h1>result: </h1>{%custom_tag {"option1":"option"}%} {{result}}
```
so this will inject the result and result will be available to liquid during runtime. is this a good/bad practice?

I've tried this approach but I just wanna double-check whether if this a good case or not
Thanks

**Comment by harttle** [comment]
Scopes are typically pushed/popped in pairs, eg. the `for` tag will push a `{forloop}` on begin tag and pop it out on end tag.

- To set a value in the current scope, use `context.scopes[context.scopes.length - 1].result = result`;
- To set a value to the root scope, use `context.scopes[0].result = result`

**Comment by Ali-Dalal** [comment]
so is it right to inject a variable to the context so it will be available in the liquid document?

in another word, let's say that we `custom_tag` fetches a user from API, and we use `context.scopes.push(user)` so the user object will be available in the template and can be accessed via `{{user}}`. Is this something right to do or now? Note: I need the `user` to be accessible across all the document so I might reference it in the beginning of the liquid page and before I end the liquid page

thanks

**Comment by harttle** [comment]
Use `context.scopes[0].result = result` to make it available for the whole page.

Note that partials included via [render tag](https://liquidjs.com/tags/render.html) can **NOT** access variables from parent template. See [the globals option](https://liquidjs.com/tutorials/options.html#globals) for this case.

**Comment by Ali-Dalal** [comment]
@harttle Thanks a lot for the help. Closing this :)
