### ISSUE TITLE
Support Array Filters

### ISSUE THREAD

**Issue by khalidabuhakmeh** [harttle/liquidjs#201]
Thank you for writing this library. I noticed it is part of the [@11ty](https://github.com/11ty/eleventy) project. I am coming from Jekyll and noticed that many of the array filters are not implemented.

https://shopify.dev/docs/liquid/reference/filters/array-filters

Are there plans to add them to LiquidJS?

**Comment by harttle** [comment]
Array filters listed on this page are all implemented (join, first, last, concat, index, map, reverse, size, sort, where, uniq), can you be more specific?

**Comment by khalidabuhakmeh** [comment]
I'm going to close this issue since I haven't tried the latest iterations. I'll clear some of the psychic weight. Thanks for this project.
