### ISSUE TITLE
Colon silently made mandatory in 9.10.0

### ISSUE THREAD

**Issue by pdl** [harttle/liquidjs#208]
It looks like the behaviour of filters has changed where there is no colon between a filter and its arguments between 9.9.0 and 9.10.0. I haven't spotted anything in the changes to indicate this was intentional. Where there is no colon after the filter name, arguments are ignored. If the original behaviour is now unsupported, I would have expected to see an error thrown.

```
echo '{{"world" | prepend "hello" }}' | npx liquidjs@9.9.0
helloworld

echo '{{"world" | prepend "hello" }}' | npx liquidjs@9.10.0
world
```

**Comment by harttle** [comment]
Thank you for the work to find it out. This case is not covered before and I'm surprised to know it worked once upon a time.

> If the original behaviour is now unsupported, I would have expected to see an error thrown.

You're right, it should be regarded illegal for `prepend` to have `undefined` to prepend. I'll throw something upon this.

**Comment by pdl** [comment]
I was actually expecting the compiler to throw a syntax error because of the extra tokens rather than just discard the tokens and call the function with no arguments. I picked prepend arbitrarily, but this approach would not help for e.g. round, which has an optional first argument:

```
echo '{{ 2.22222 | round 2 }}' | npx liquidjs@9.9.0
2.22

echo '{{ 2.22222 | round 2 }}' | npx liquidjs@9.10.0
2
```

I would be worried that anyone who has missed the colon might not notice that the argument has not been passed to round at all.

**Comment by harttle** [comment]
It's intentional in Liquid to be safe and customer facing. I tried the Ruby version both the following renders to `3` (even with `strict_filters=true` which I guess throws only when filter not defined):

```liquid
'{{ 3.456 | round }}'
'{{ 3.456 | round 2 }}'
'{{ 3.456 | round 2 a b c ? }}'
```

**Comment by pdl** [comment]
I see! I guess it makes sense to be consistent. Thank you for confirming, and so quickly, too.
