### ISSUE TITLE
Is React demo really working as expected?

### ISSUE THREAD

**Issue by mkbctrl** [harttle/liquidjs#217]
Maybe I am not getting it right @harttle. Hopefully you will be able to confirm.

LiquidJS is meant to output `.liquid` file from `.js` file, not the other way around right?
Cause react demo works in the opposite way. Any changes in the `'.liquid` file are reflected in React app, but it doesn't work in opposite direction.

Maybe I am doing smth wrong 🤔 

Nevertheless your project looks like what I am looking for. I want to create shopify theme and only generate `.liquid` files from `.js` files. Plain TS/JS would be already great, but if it's possible to mix it with react it would be even better.

Looking forward to some info on that matter. Thanks in advance.

**Comment by harttle** [comment]
> LiquidJS is meant to output .liquid file from .js file

LiquidJS is meant to transform Liquid template string or .liquid file to HTML string. The react demo demonstrates how to transform .liquid files to HTML fragments which is inserted into React DOM.

**Comment by mkbctrl** [comment]
Thanks a lot for clarification. It looks like I need to expand my search. Are you aware of any tools that might help in achieving this goal?

**Comment by harttle** [comment]
Sadly no. ❤️
