### ISSUE TITLE
Truncate does not work if liquid has non-breaking spaces in 9.11.10

### ISSUE THREAD

**Issue by villesau** [harttle/liquidjs#221]
Hi,

Seems that the latest version does not truncate words.
```
var Liquid = require("liquidjs").Liquid
const engine = new Liquid({ strictVariables: true, strictFilters: true });
console.log(engine.parseAndRenderSync("{{huh | truncate: 11}}", {huh: "fdsafdsafdsafdsaaaaa"}))

```

Should result `fdsafdsafds`, but results `fdsafdsafdsafdsaaaaa`

working version: 9.6.0
failing version: 9.11.10

**Comment by harttle** [comment]
I can't reproduce, do I miss something? See the snippet on repl.it: https://repl.it/repls/NuttyNavajowhiteRatio

**Comment by villesau** [comment]
@harttle The issue seems to be with non-breaking space in the snippet, and Github fails to copy-paste that. If you can edit the message, copy it from editing mode.

**Comment by harttle** [comment]
Interesting! Now I can reproduce and I'll try to include all unicode space characters. The regression is caused by replacing `\s` in RegExp with a manual tokenizer in #205.

**Comment by villesau** [comment]
Thanks a lot @harttle! I debugged this yesterday and I have to say it was super hard since there were nothing visibly wrong with the liquid :D
