### ISSUE TITLE
Support function calls

### ISSUE THREAD

**Issue by romaricpascal** [harttle/liquidjs#222]
Hello,

I was wondering if there was plan for supporting function calls inside the templates.

- rendering the value `{{obj.property()}}` breaks with `unexpected token at "()"`. Can be worked around with an `apply` filter `{{obj.property | apply}}` but it's not really straightforward
- `assign` breaks with the same error
- `if` , `for` and `case` don't break but seem to ignore the returned value

That would be ideal to avoid too much gymnastics (and I guess allow what's already possible in Ruby, as function calls don't necessarily need parenthesis, or does Liquid break that behaviour?)

Cheers :)

**Comment by harttle** [comment]
Sounds reasonable. I prefer the `{{obj.property}}` approach, in which we should check if it's a function before reading its value.

**Comment by rhumaric** [comment]
Do you mean check if the property is a function and invoke it automatically? I like that! Wouldn't that leave out all the functions that need parameters out though?

**Comment by harttle** [comment]
I'm not sure if that's the behavior for shopify/liquid, but we definitely should align to that behavior whenever possible. I'll dig into it later, and any kind of PR is welcome.
