### ISSUE TITLE
Whitespace in square brackets should be ignored

### ISSUE THREAD

**Issue by falldowngoboone** [harttle/liquidjs#224]
Recently when converting a Nunjucks template to Liquid, I ran into an issue with whitespaces inside of square bracket notation.

```
variable[ key ]
```

👆 The above code does what I would expect in Nunjucks and accesses the value associated with the string to which `key` is set. In Liquid, however, the value is `variable` itself. Not sure if this is a known issue, but I could not find information anywhere about this.

I would expect the above should work without having to remove whitespace. My question is, can anyone reproduce this, and, if they can, could this be fixed?

**Note:** I have filed this at Shopify/liquid#1242 as well. I am filing it here at the suggestion of @zachleat.

**Comment by harttle** [comment]
The `variable[ key ]` syntax seems resonable, I'll fix it soon.

**Comment by harttle** [comment]
I can't reproduce this in both output and if tag, see https://jsfiddle.net/L4y301sm/ . Can you provide a tiny snippet to reproduce this?

I guess it maybe the same issue as #221? Try replace that space with ordinary `<space>` which ASCII code is 32. If that's the case it'll be fixed soon.

**Comment by falldowngoboone** [comment]
Hi, @harttle, I am unable to reproduce on my end now. It's probably because I had other errors in my template that were causing some strange behavior and, for whatever reason, taking the spaces out of the key "fixed" it. That's what I get for not creating a reduced test case. Sorry about that.
