### ISSUE TITLE
Is there a support / planned support for async filters?

### ISSUE THREAD

**Issue by kyrisu** [harttle/liquidjs#232]
I'm trying to refactor my code that is currently using [liquid module](https://github.com/docs/liquid) to use liquidjs and one thing I'm missing are async filters. Something that would allow me to do:
```
{{ userId | get_user_data | json }}
``` 
where `get_user_data` is an async function calling external API. 

Is something like this currently possible? Any workaround that could make this possible?

I've looked through the docs and tickets and the only thing I've found is the async context resolution.

**Comment by harttle** [comment]
Filters cannot be async currently, but we do support async drops, see this test case:

https://github.com/harttle/liquidjs/blob/master/test/integration/drop/drop.ts#L48

**Comment by harttle** [comment]
https://github.com/harttle/liquidjs/commit/e36f3ff291e0db498a99c6144226e721cce21084#diff-71eabdbbe46170b7a8dff0f6fde49d0bR25-R35
