### ISSUE TITLE
ExpressJS + LiquidJS + Shopify Theme = Possible?

### ISSUE THREAD

**Issue by rwmml** [harttle/liquidjs#241]
I have been banging my head trying to get a shopify theme to work with liquidjs. I can render a simple page, but not one with any actual content. When I try to render the layout/theme.liquid file, via res.render('layout/theme', liquid_obj) i get a tag error for 'header';

I also feel like I am missing something important, specifically the shopify liquid object schema and how a pages' content is rendered.

Is there a tutorial on how to implement a shopify theme with express and liquid that has the necessary shopify liquid object?

sample code: 

app.js
`const engine = new Liquid();

app.engine('liquid', engine.express());

app.set('views', ['/themes/my_theme']);

app.set('view engine', 'liquid');`

routes/page.js
`res.render('templates/index', {shop: {name: 'test'});`

**Comment by harttle** [comment]
It's not working out of the box. LiquidJS implements the template engine part of Shopify, but not the platform-specific objects such as `paginate`, `products`, etc. And there's no *theme* concept in LiquidJS.

I believe it can be implemented via the [Plugin API](https://liquidjs.com/tutorials/plugins.html) but not sure whether or not there is such a plugin already.
