### ISSUE TITLE
Expose tokenizer

### ISSUE THREAD

**Issue by bigelowcc** [harttle/liquidjs#245]
Prior to 9.10.0 I was cheekily using the tokenizer that was attached to the engine when I imported the package. In 9.10.0 there was a refactor that hid the tokenizer. 

Would it be possible to have this as something that I can import? I'm currently using to to tokenize liquid files and translate them between Jekyll and Liquidjs fomatting.

**Comment by harttle** [comment]
You can still import the tokenizer but its usage can be different.

```javascript
const { Tokenizer } = require('liquidjs');
// or in ES modules:
// import { Tokenizer } from 'liquidjs'

const tokenizer = new Tokenizer('{{foo}}', '/tmp/foo.liquid')
const tokens = tokenizer.readTopLevelTokens()
console.log(tokens)
/* Outputs:
[ OutputToken {
    kind: 8,
    input: '{{foo}}',
    begin: 0,
    end: 7,
    file: '/tmp/foo.liquid',
    trimLeft: false,
    trimRight: false,
    content: 'foo' } ]
*/
```

See https://liquidjs.com/api/classes/parser_tokenizer_.tokenizer.html for details. Hope it helps!

**Comment by bigelowcc** [comment]
Fantastic, thanks for that. All working again now.
