### ISSUE TITLE
Handling DoS loops or max time processing

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#250]
Are there any recommended best practices or ways to put limits on the number of cycles the render function can take?  For example, if a malicious user adds nested for loops with very large max lengths, how do you prevent this from taking up the entire CPU?

I've been searching around and haven't found any questions related to this, so I feel like I'm probably missing something obvious.

**Comment by harttle** [comment]
Not available currently. But I think it's OK to have this feature, are there any other libs implementing this, for reference?

**Comment by amit777** [comment]
I think I have a solution using a slightly patched paralleljs which uses webworkers.  I will post the example here as soon as my patch is merged.  But it's potentially pretty simple.

**Comment by amit777** [comment]
paralleljs v1.10.0 has my pull request merged in.   You can pass opts.timeout to the Paralleljs's spawn method and call Liquidjs's render function within it.

**Comment by harttle** [comment]
I guess limiting the processing time is better handled by external libraries. Closing this issue.

**Comment by denis-isaev** [comment]
If this library doesn't have limits as the Shopify version does, then why is it called **safe**?

**Comment by harttle** [comment]
I thought Shopify doesn't have a limit on this. Will investigate whether we can do the same.

**Comment by harttle** [comment]
Added DoS related support: https://liquidjs.com/tutorials/dos.html
