### ISSUE TITLE
Parsing or injecting Liquidjs each output rendered to HTML

### ISSUE THREAD

**Issue by pabliqe** [harttle/liquidjs#251]
Hello, I'm wondering if there a way to parse each output renderer by Liquidjs.

I was looking at the code and thinking this could be achieved by using a `base filter` that applies to every {{}} or maybe having a callback like `onRender()` but couldn't find any clues yet.

What I'm trying to achieve here is adding and ID span tag to every output, something like this:

```html
<div>{{ data }}</div>
<!-- converts to -->
<div><span liquid-id="xxx">Data</span></div>
```

Could you please let me know if there's any other workaround?

Thanks in advance 🙏

**Comment by harttle** [comment]
If I understand correctly, you're trying to parse all Output(`{{}}`)s in the rendered text. That's not possible without re-writing the [output.ts](https://github.com/harttle/liquidjs/blob/0cd4d87d463b6e4772c9472def972f7cfef7f84f/src/template/output.ts#L18). But there's workaround just as you mentioned.

A simple but stupid way is introduce a filter that renders a span from a string, like:

```liquid
<div>{{ data | span }}</div>
```

Another option is recursively replace every string value of the context object to a custom Drop:

```javascript
const { Liquid, Drop } = require('liquidjs')
const engine = new Liquid()
const ctx = transform({ foo: 'foo' })

const html = engine.parseAndRenderSync('{{foo}}', ctx)
console.log(html)

function transform (obj) {
  class MyDrop extends Drop {
    constructor (text) {
      super()
      this.text = text
    }
    valueOf () {
      return `<span>${this.text}</span>`
    }
  }
  for (const [key, val] of Object.entries(obj)) {
    if (typeof val === 'string') {
      obj[key] = new MyDrop(val)
    }
    return obj
  }
}
```

**Comment by pabliqe** [comment]
That’s right, in this case adding a `span` filter to every tag since I want to handle it from the background process.

I’ll dig in your second option making a transform of every data variable.

Thanks you so much @harttle 🙏
