### ISSUE TITLE
Custom isFalsy definition

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#255]
Hi! I would like isFalsy to match more closely with JavaScript's false definition. Would it be possible to add a feature to override the default isFalsy() definition as an option to the constructor?

**Comment by harttle** [comment]
Not available now. I think an additional `JSTrusy` option is better cause I can't think of other cases.

**Comment by amit777** [comment]
We are planning on using a Perl liquid template implementation that shares templates with nodejs. It also has a slightly different truthy implementation which is closer to JS. So I was hoping to normalize them both.

**Comment by amit777** [comment]
My typescript knowledge is not so good,  I was trying to figure out a way to pass the liquid options into boolean.ts isFalsy() function.  Would you be able to provide a pointer?  I can update docs, tests and code and create pull request after.

**Comment by harttle** [comment]
A simple (direct) approach would be:

- add an additional `ctx: Context` argument to `src/render/boolean.ts#isTruthy()`, and make use of `ctx.opts.isTruthy`.
- pass the context to `operatorImpls` (then passes `isTruthy()`) to  in `src/render/expression.ts#evalOperatorToken()`
- similarly, pass contexts in `src/builtin/filters/array.ts#where()` and `src/builtin/tags/if.ts#render()`

That would be enough. Let me know if you get stuck.
