### ISSUE TITLE
How to npm install from github repo

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#256]
Normally I can install projects that are published on NPM by visiting their github repo and just running npm install on the URL like this:
```
npm install https://github.com/harttle/liquidjs.git
```

However, this doesnt seem to create a node_modules/liquidjs folder that contains dist assets.  Is there a recommended way to be able to test out master?

**Comment by harttle** [comment]
For local development, build and link liquidjs:

```bash
npm install
npm run build
npm link
```

Then run `npm link liquidjs` in your repo. Or just install the latest version from npm since liquidjs runs autopublish whenever a feature or bugfix pushed.
