### ISSUE TITLE
missed filter not throwing parse error

### ISSUE THREAD

**Issue by palsorbo** [harttle/liquidjs#271]
Hii !

Facing an issue can you help me out. 

Running `{{ data_due_date | default:'Nov 30' date:'%b %d' }}` template on liqp throws  parse error. 

`Exception in thread "main" liqp.exceptions.LiquidException: parser error "extraneous input 'date' expecting {OutEnd, '|'}" on line 1, index 36`.

But running the same template with liquidjs engine throws no parse error. Is this a bug?

Thank you.

**Comment by harttle** [comment]
There is a [strictFilters](https://liquidjs.com/api/interfaces/liquid_options_.liquidoptions.html#Optional-strictFilters) option available, here's a demo: https://jsfiddle.net/kxetzqh5/

**Comment by palsorbo** [comment]
Hey, thank you for the quick response.

Here added a demo: [https://jsfiddle.net/sarbajit/hrxmsedp/7/](url)

In the second h3 tag the parsing fails in Liqp.

**Comment by harttle** [comment]
Thank you for clarification. If I understand correctly, it's about how to handle invalid filter syntax. The content of the second h3 in the jsfiddle above is:

```liquid
{{ age | default: 'now'  date: '%d'}}    // missing `|` before `date`
```

- shopify/liquid throws `wrong number of arguments`
- liqp throws `parser error "extraneous input 'date'`
- liquidjs just skips the intended `date` filter

It's indeed invalid syntax, so I'm considering throw an ParseError maybe `invalid argument` or `unexpected ":"` and it should be thrown regardless the value of [strictFilters](https://liquidjs.com/api/interfaces/liquid_options_.liquidoptions.html#Optional-strictFilters).
