### ISSUE TITLE
Passing liquid in FilterImpl

### ISSUE THREAD

**Issue by almousa1990** [harttle/liquidjs#277]
Hello,

It would be very useful to pass liquid to filter implementation, to allow parsing and rendering filtered object.

Use case:
A translate filter 't' takes a template string like "hello {name}" and a name arg, when current implementation, it not possible parse the string with the given scope.

**Comment by harttle** [comment]
It's easy to add liquid to `this`, but it maybe not as useful as you think. Since the `{% raw %}` tag is the only way to escape in Liquid, the following template is invalid:

```liquid
{{ "hello {{name}}" | render: "foo" }}  // {{ foo }}s are not allowed to be nested
```
