### ISSUE TITLE
Filters don't work in expressions

### ISSUE THREAD

**Issue by almousa1990** [harttle/liquidjs#287]
Hi,

For some reasons, filters don't seem to work when evaluating and expressions, for example, the following will always evaluate (with filters):
```
{% assign people = "alice, bob, carol" | split: ", " -%}
{%- if people | size == 1 -%}shouldn't evaulate{%- endif%}
```

The following will not evaluate:
```
{% assign people = "alice, bob, carol" | split: ", " -%}
{%- if people.size == 1 -%}shouldn't evaulate{%- endif%}
```

Note that both conditions should have the same outcome

**Comment by harttle** [comment]
I tried the Ruby version just to find it doesn't support this too. But I'm happy to have this feature in LiquidJS. I'll keep this open till someone implement it.

**Comment by harttle** [comment]
The operator priority is another potential issue to use filters in expressions.

```liquid
{{ foo | bar: 'a'  ==  'b' }}  // one may expect == has higher priority
{{ people | size == 1 }}     // one may expect '|' has higher priority
```

But I managed to make this work (the `|` always has higher priority, which is more intuitive and compliant to the current implementation):

https://github.com/harttle/liquidjs/blob/24306722ecb3c7274671524a03def7e6c39457cb/test/integration/builtin/tags/if.ts#L84-L89
