### ISSUE TITLE
Unexpected behavior when string literals contain }}

### ISSUE THREAD

**Issue by jolleekin** [harttle/liquidjs#288]
### Input
```liquid
{{ '{{' }}
{{ '}}' }}
```

### [Actual output](https://liquidjs.com/playground.html#e3sgJ3t7JyB9fQp7eyAnfX0nIH19)
```
{{
' }}
```

### Expected output
```
{{
}}
```

The issue is at [tokenizer.ts, line 133](https://github.com/harttle/liquidjs/blob/master/src/parser/tokenizer.ts#L133)

**Comment by harttle** [comment]
It's by design. To output raw string literals, use [raw](https://liquidjs.com/tags/raw.html):

```liquid
{% raw %}{{{% endraw %}
{% raw %}}}{% endraw %}
```
