### ISSUE TITLE
Custom operators for conditionals

### ISSUE THREAD

**Issue by JasonEtco** [harttle/liquidjs#300]
Hello! I have a bit of a weird feature request - we'd like to use this library for https://docs.github.com instead of [docs/liquid](https://github.com/docs/liquid), and for the most part it all works exactly the same way with a couple of minor API tweaks 🎉 However, there's one (admittedly hacky) feature that we depend on.

We have custom operators for conditionals - they aren't super complex, but we use them in thousands of markdown files. For example:

```js
Liquid.Condition.operators.ver_gt = (cond, left, right) => {
  if (!matchesVersionString(left)) return false
  if (!matchesVersionString(right)) return false

  const [leftPlan, leftRelease] = splitVersion(left)
  const [rightPlan, rightRelease] = splitVersion(right)

  if (leftPlan !== rightPlan) return false

  return semver.gt(semver.coerce(leftRelease), semver.coerce(rightRelease))
}
```

The actual behavior isn't super relevant - ultimately, it takes the same arguments as other conditionals and returns a boolean. In `docs/liquid` we're able to add properties to `Liquid.Condition.operators`; but the equivalent list isn't exposed in `liquidjs`. I believe that'd be [`/src/render/operator.ts`](https://github.com/harttle/liquidjs/blob/master/src/render/operator.ts).

What do y'all think about exposing that somewhere, potentially on the engine or as an option? Something like:

```js
new Liquid({
  operators: {
    ...liquid.operators,
    ver_gt: function () {}
  }
})
```

### Other options I've considered

Since I realize that's a bit of a weird one, I did try some other things. Filters don't work in the same way - you can't inline a conditional:

```js
const { Liquid } = require('liquidjs')
const semver = require('semver')
const engine = new Liquid()
engine.registerFilter('ver_gt', (left, right) => semver.gt(left, right))
const template = '{% if currentVersion | ver_gt: "3.0.0" %}True{% else %}False{% endif %}'

// 2.0.0 is _not_ greater than 3.0.0
engine.parseAndRender(template, { currentVersion: '2.0.0' }).then(console.log)
// -> True
```

We can do that via an `assign` on a separate line:

```js
const template = '{% assign isGt = currentVersion | ver_gt: "3.0.0" %}{% if isGt %}True{% else %}False{% endif %}'
```

But then it gets real verbose; there are about 700 cases of our custom `ver_lt` and `ver_gt` operators in the [github/docs](https://github.com/github/docs) codebase. If I'm missing something to make the first example work, please let me know!

I'd be happy to work with y'all to open a PR for exposing the operators in a way that we can tack custom ones on, or see if we can get the filter to work directly in the `if`. Let me know what you think!

**Comment by harttle** [comment]
It's great to have the proposed `operators` option except that `liquid.operators` should be static, like `import {Operators} from 'liquidjs`.

```javascript
new Liquid({
  operators: {
    ...Operators,
    '>': function () {}
  }
})
```

>  believe that'd be /src/render/operator.ts

You're right, it's there.

> see if we can get the filter to work directly in the if

I can take care of this if you want, there's already an issue here: https://github.com/harttle/liquidjs/issues/287

**Comment by JasonEtco** [comment]
Thanks @harttle 🙏 I can open a PR for adding a static `Operators` export, and bubbling down the `operators` option to the constructor. That'd be our preferred way to solve this use-case for sure, so that we don't have to modify our ~1500 markdown files 😅 

That said, #287 does seem like a really good fix in general!
