### ISSUE TITLE
[docs] Add version numbers to filters/tags docs for when item was added?

### ISSUE THREAD

**Issue by pdehaan** [harttle/liquidjs#305]
Currently 11ty (on npm) uses an older version of LiquidJS@6.4.3 (although this is fixed in GitHub and will updated to ^9.16.1 when eleventy v1.0.0 gets published to npm).

| &nbsp; | @11ty/eleventy | liquidjs | Install
|:-------|:---------------|:---------|:-----------
| npm (latest) | 0.11.1 | 6.4.3 | <kbd>npm i @11ty/eleventy -D</kbd>
| GitHub | 1.0.0-beta.0 | ^9.16.1 | <kbd>npm i github:11ty/eleventy -D</kbd>

But it can be confusing when reading the LiquidJS docs and you aren't sure which filters are supported by which versions of LiquidJS. Not sure if there's an easy way to flag which version of LiquidJS added the `where` filter (spoiler alert: it was v8.1.0). Usually I have to look at releases or git history. Not sure if there's an easier way.

**Comment by harttle** [comment]
Makes sense. I can update the docs to contain that information.

**Comment by harttle** [comment]
Now the version number will be shown in filters/tags API docs. eg. https://liquidjs.com/filters/where.html

**Comment by harttle** [comment]
Newly added features within each tag/filter like [Jekyll include](https://liquidjs.com/tags/include.html#Jekyll-include) also has a `Added in:` section.

But I was not able to track history changes within tags/filters, that remains to be unknown. Hopefully now we have a baseline for this point in docs, future work will be well documented.
