### ISSUE TITLE
newline_to_br filter should output <br /> instead of <br/>

### ISSUE THREAD

**Issue by amarsyla** [harttle/liquidjs#320]
The `newline_to_br` filter should output `<br />` instead of `<br/>` - https://shopify.github.io/liquid/filters/newline_to_br/

Trying to split a multi-line string will fail in LiquidJS, but will work in Shopify Liquid.

Example usage:

```
{{ 'a \n b \n c' | newline_to_br | split: '<br />' }}
```

**Comment by harttle** [comment]
It seems that the `\n` should be preserved also.

**Comment by harttle** [comment]
Considering we need to respect the `.toString()` method when stringify, we can't stringify arrays in the same manner as in Ruby. The output of LiquidJS would be

```
a ,
 b ,
 c
```

instead of:

```
a 
 b 
 c
```
