### ISSUE TITLE
How to disable built-in filters/tags?

### ISSUE THREAD

**Issue by azu** [harttle/liquidjs#324]
I want to disable some built-in filters and tags.
However, liquidjs provides only register API.

https://liquidjs.com/tutorials/register-filters-tags.html

For example, I want to disable `include` for unused my app.

My workaround: override `include` tag after initializing.

```js
import { Liquid } from "liquidjs";

const engine = new Liquid();
engine.registerTag("include", {
    parse: function() {
        throw new Error("Disable include");
    },
    render: async function() {
        throw new Error("Disable include");
    }
});
const tpl = engine.parse("{% include 'footer.liquid' %}");

engine.render(tpl, { v: "Liquid" }).then(console.log);
```

**Comment by harttle** [comment]
The following looks better:

```
const disabled = {
    parse: function(token) {
        throw new Error(`tag "${token.name}" disabled`);
    }
}
engine.registerTag("include", disabled);
```

I can provide an option to create a bare Liquid instance with no filters/tags, but it would be too verbose to allow disabling each of them. Let's see if anyone else need this.

**Comment by azu** [comment]
In my app, I will disable `render`, `layout`, `include`, `cycle`, and `tablerow`.
My app does not need HTML-specific features, also this template will be written by a user.
So, I will disable these for reducing attack-surface.

I wish that all built-in filters and tags would be configurable by allowing a list.
However, It may be reasonable that does not provide this option because [Liquid](https://shopify.github.io/liquid/) does not has the same one.

**Option 1:**

- Add a disabling feature like `unRegisterTag` function
  - It is a deny list way

The current workaround is a similar one to this.

**Option 2:**

- Passing `builtinFilters` and `builtinTags` as constructor options.
  - It is an allow list way

https://github.com/harttle/liquidjs/blob/2f059f6a2518975879bd4a8d8c98937676869968/src/liquid.ts#L34-L35

```js
const engine = new Liquid({
  builtinTags: ["for", "if"],
  builtinFilters: ["json", "URL"], // TODO: 
});
```

**Option 3:**

- Just documentation
  - Add a workaround to the documentation

**Comment by harttle** [comment]
Option 3 looks good to me. Published at https://liquidjs.com/tutorials/register-filters-tags.html#Unregister-Tags-Filters . Thank you for your pursuit! It would be useful.

**Comment by azu** [comment]
Thanks!

We can close this issue.
