### ISSUE TITLE
for..in with Object works differently than Shopify

### ISSUE THREAD

**Issue by wbaaron** [harttle/liquidjs#33]
In Shopify's liquid implementation, each iteration of a for..in loop supplies the next value of the object.
See example: https://help.shopify.com/themes/liquid/tags/iteration-tags#for

This module differs in that it supplies the next key of the object instead. This is arguably better, since in Shopify's implementation you don't even have access to the key, and in this module you can always just use object[key] to get the value. However, it still differs from how Shopify handles it, which leads to confusion, and templates needing to be adjusted.

Is this difference by design, or just an oversight?

If it's an oversight, then the test here:
https://github.com/harttle/shopify-liquid/blob/master/test/tags/for.js#L27
should be corrected.

Line 30 should read:
`.to.eventually.equal('bar-haa-')`
instead of
`.to.eventually.equal('foo-coo-')`

Thanks!

**Comment by harttle** [comment]
I'm not sure about this. So I did some test on the ruby version:

```ruby
logger = Logger.new(STDOUT)
@template = Liquid::Template.parse("{% for i in person %}{{i}}-{% endfor %}")
logger.info(@template.render('person' => {'name' => 'alice', 'age' => 17}))
```

and got output like this:

```
I, [2017-07-15T09:56:19.840003 #21556]  INFO -- : namealice-age17-
```

does this means that it output a concatenation of the key and the value?

**Comment by harttle** [comment]
Since this behavior of liquid is not documented, whether to iterate over keys or values still need to be discussed. Any thoughts?

**Comment by harttle** [comment]
Closing, since no documented difference found.
