### ISSUE TITLE
Passing object literals via filters?

### ISSUE THREAD

**Issue by pdehaan** [harttle/liquidjs#365]
Is it possible to pass an object literal via a filter? For example: `{{name | make_big_case: {color:"red"} }}`. It seems to work in Nunjucks, but I don't have any experience w/ Shopify's Liquid implementation to know if it's supported upstream, or just wishful thinking.

I tried with the snippet below, where I pass `{color: "red"}` as an argument in my filter, but by the time the filter logs the arguments, it is `undefined` and my default value of an empty object takes over. It works as expected if I pass a simple string/number/Boolean value, so this seems Object [and Array] specific.

```js
const { Liquid } = require('liquidjs');
const engine = new Liquid();

engine.registerFilter('make_big_case', (v, opts={}) => {
  console.log({v, opts});
  return v.toUpperCase();
});

engine
    .parseAndRender('{{name | make_big_case: {color:"red"} }}', {name: 'alice'})
    .then(console.log); // outputs 'Alice'
```
&mdash; https://npm.runkit.com/liquidjs

I'm getting the following output:

```
Object {v: "alice", opts: Object {}}
"ALICE"
```

Interestingly, if I try passing an array: `{{ name | make_big_case: [1,2,3] }}`, then my custom filter logs the following arguments:

```js
{
  v: "alice"
  opts: 2
}
```

Not sure why `[1,2,3]` gets converted to `2`. I doesn't look like the array length or anything else immediately obvious to me.

**Comment by harttle** [comment]
Investigate a bit into this. Find shopify/liquid also don't support JSON/JS object literal, will throw something like:

```
{color:"red"}' was not properly terminated with regexp: /\\}\\}/
// seems it's trying to parse it as {{ some_value }}
```

In current LiquidJS implementation, Liquid literals are quite different from JSON literal, would be nontrivial work and may not be compatible.

For workaround, there's the `:` syntax for **named filter arguments**:

```javascript
const { Liquid } = require('liquidjs');
const engine = new Liquid();

engine.registerFilter('make_big_case', (v, ...args) => {
  return args
});

engine
    .parseAndRender('{{name | make_big_case: foo:name, "coo" | json }}', {name: 'alice'})
    .then(console.log); // outputs "[["foo","alice"],"coo"]
```

And `range()` literal to declare an Array in Liquid:

```liquid
// outputs 1-2-3-4-5
{{ foo | default: (1, 5) | join: '-' }}
```

See https://liquidjs.com/playground.html#e3sgZm9vIHwgZGVmYXVsdDogKDEsIDUpIHwgam9pbjogJy0nIH19,e30=
