### ISSUE TITLE
About the "fs" option, is "readFileSync" optional ?

### ISSUE THREAD

**Issue by Khalilbz** [harttle/liquidjs#368]
Hi, please I wan to know if the "readFileSync" is optional, because I'm importing "includes" from the database.
So it's working without setting it, like so :
```
// Initializing Liquid
    const engine = new Liquid({
      lenientIf: false,
      fs: {
        // readFileSync(file) {
        //   return getTemplate(file);
        // },
        async readFile(file) {
          return getTemplate(file);
        },
        existsSync() {
          return true;
        },
        async exists() {
          return true;
        },
        resolve(root, file, ext) {
          return file;
        }
      },
   });
```
But i'm afraid that it may cause feature errors.
and if it's not optional, any workaround to do it, because I have to fire a DB request at every include.
I came here because I read every part of the documentations and didn't find an answer.

**Comment by harttle** [comment]
It's called only when `renderSync()`. I'll make it clear in the document.

**Comment by Khalilbz** [comment]
Thank you so much
