### ISSUE TITLE
strftime but with UTC values?

### ISSUE THREAD

**Issue by zachleat** [harttle/liquidjs#375]
Marginally related to https://github.com/harttle/liquidjs/issues/236

When you pass in a JS Date object to the date filter https://github.com/harttle/liquidjs/blob/b5a22fa0910c708fe7881ef170ed44d3594e18f3/src/builtin/filters/date.ts#L5 it does local time zone conversion in the output.

This has unexpected results!

When a `Date` instance representing this: `2016-02-01T00:00:00.000Z` (timestamp `1454284800000`) is passed to the date filter like this:

```
{{ page.date | date: '%Y/%m/%d' }}
```

The output is `2016/01/31` and not `2016/02/01` like I would expect.

Is there a way to use UTC all the way through? For example, I want https://github.com/harttle/liquidjs/blob/b5a22fa0910c708fe7881ef170ed44d3594e18f3/src/util/strftime.ts#L107 but with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMonth instead

**Comment by harttle** [comment]
Thank you for the elaboration. It's actually a tricky problem in JavaScript especially for LiquidJS. 

As discussed in #236, in the Liquid language implemented by Ruby, a Date object has a timezone data field so each Date can be formatted using it's corresponding timezone. For JavaScript, Date is just a number without timezone infomation. So what we can do is provide a format timezone, default to local timezone to be compatible.

Will that address the problem for you? How do you think?

**Comment by zachleat** [comment]
Yeah! Assuming that I can pass in like a "Z" or something to specify UTC right?

**Comment by harttle** [comment]
Yes. Can be done as a construction parameter or on each filter use. I prefer the former when someone actually need to specify per use we then consider the latter.

**Comment by harttle** [comment]
Added support for `timezoneOffset` to customize date timezone, and `preserveTimezones` to preserve literal Date values, please refer to https://liquidjs.com/tutorials/options.html#Date for details.
