### ISSUE TITLE
size filter does not respect Objects

### ISSUE THREAD

**Issue by takase1121** [harttle/liquidjs#385]
Based on the [original ruby implementation][1], `size` should be able to get size of Objects. 
`.size` works on both Hash and Array.

This is currently not the case here. `.length` doesn't work for Objects here.

Do we follow Ruby's "buggy" behavior or the "correct" behavior defined by the docs?

[1]: https://github.com/Shopify/liquid/blob/aa8ce87b96a162c692a03edeae292ca5c7f76d61/lib/liquid/standardfilters.rb#L27

**Comment by harttle** [comment]
Should be supported. Idealy same template should work in both Ruby and Node.js. We'll do it as long as we can.
