### ISSUE TITLE
Filter to dynamically render a string variable

### ISSUE THREAD

**Issue by PlanetIrata** [harttle/liquidjs#386]
Hi,

Is there a way to dynamically render the content of a string ?

Suppose that I have this data:

```javascript
data = {
  name: "Yann",
  dynamicContent: "Hello, my name is {{ data.name }}"
}
```

And this `test.liquid` file rendered by a Tag `{% render test.liquid data: data %}`

```html
{{ data.dynamicContent }}
```

The output will be:

```html
Hello, my name is {{ data.name }}
```

And not:

```html
Hello, my name is Yann
```

Is there a way to write a filter like this ?

```html
{{ data.dynamicContent | render_me_please }}
```

Thank for your help!

**Comment by harttle** [comment]
You can call liquid render inside filter implementation, like:

```javascript
  engine.registerFilter("dynamic", function(str) {
    return this.liquid.parseAndRender(str, this.context.getAll())
  })

  const html = await engine.parseAndRender(
    `{{ str | dynamic }}`,
    {str: "Before {{foo}} After", foo: "FOO"}
  )
  contentEl.innerText = html
```
Here's a jsfiddle: https://jsfiddle.net/drmn6a18/1/ If you want to make it more efficient, remove overhead of calling `this.context.getAll()`, you'll need to call `this.liquid.parse` and `this.liquid.renderer` manually.

**Comment by PlanetIrata** [comment]
Thx!
