### ISSUE TITLE
Assign when applying filters to the value to story

### ISSUE THREAD

**Issue by BarryCarlyon** [harttle/liquidjs#39]
Consider this block of code

```
      {% assign transaction_size = 0 %}
      {% for transaction in transactions %}
KIND {{ transaction.kind }}<br />
        {% unless transaction.kind == "capture" or transaction.kind == "void" %}
ADDING FROM {{ transaction_size }}<br />
          {% assign transaction_size = transaction_size | plus: 1 %}
ADDING TO {{ transaction_size }}<br />
        {% endunless %}
      {% endfor %}
```

transaction_size is still 0, where as the loop should result intransaction_size being 2

Adjusting assign.js

```
    liquid.registerTag('assign', {
        parse: function(token){
            var match = token.args.match(re);
            assert(match, `illegal token ${token.raw}`);
            this.key = match[1];
            console.log('KEY IS ' + '|' + this.key + '|');
            this.value = match[2];
            console.log('VALUE IS |' + this.value + '|');
        },
        render: function(scope) {
            scope.set(this.key, liquid.evalOutput(this.value, scope));
            return Promise.resolve('');
        }
    });
```

Result is:

Console:
```
KEY IS |transaction_size|
VALUE IS | 0|
KEY IS |transaction_size|
VALUE IS | transaction_size | plus: 1|
```

render:
```
KIND paid
ADDING FROM 0
ADDING TO 1
KIND refund
ADDING FROM 0
ADDING TO 1
COUNT 0
```

assign doesn't seem to be applying filters to the right hand side before storing I think?!

About to attempt to debug/fix, but I'm getting pulled all over the place at $dayjob so raising the issue

**Comment by harttle** [comment]
Confirmed this is a bug. The newly created test case https://github.com/harttle/liquidjs/commit/21af8c4d7a151f1330b2d9d1f6b59f8172e8524e?diff=unified#diff-97c98a523ba7e1f3934b0a7b5049367bR42 describes your situation. 

This bug occurs when trying to write parent scope's variable, which is addressed in the current version. Published @1.9.5.

Thank you for your report.
