### ISSUE TITLE
v9.26.0 requires stream and no longer bundles for browser 

### ISSUE THREAD

**Issue by bglw** [harttle/liquidjs#396]
As of 9.26.0 a `require('stream')` was introduced, which no longer bundles for the browser through esbuild without extra configuration.

See error:
```
 > node_modules/liquidjs/dist/liquid.browser.esm.js:1701:35: error: Could not resolve "stream" (use "platform: 'node'" when building for node)
    1701 │         this.stream = new (require('stream').PassThrough)();
         ╵                              
```

Introduced in the source here: https://github.com/harttle/liquidjs/blob/aea34418de24cb85ea1acddf68c3683ce7fc9fa8/src/emitters/streamed-emitter.ts#L5

It would be great if this could be remedied somehow — I have packages in the wild which have only a major pin on liquidjs, which will now be failing upon a fresh install

**Comment by harttle** [comment]
I'll remove it from the ESM build, should be working then.

**Comment by harttle** [comment]
Try 9.27, hope it works :)

**Comment by bglw** [comment]
It does, thanks! 🙂
