### ISSUE TITLE
`concat` filter missing from documentation

### ISSUE THREAD

**Issue by floofnoodlecode** [harttle/liquidjs#397]
The array built-in filter `concat` is missing from the documentation:
https://liquidjs.com/filters/overview.html

**Comment by harttle** [comment]
Good catch!

**Comment by harttle** [comment]
Now fixed, need refresh twice (it's service worker enabled and uses local first strategry): https://liquidjs.com/filters/concat.html

**Comment by floofnoodlecode** [comment]
That's great. One nitpick. Shouldn't `concat` appear after `compact` in the left panel?

![2021-10-06 14_06_04-Filters _ LiquidJS](https://user-images.githubusercontent.com/86855208/136191314-25897582-34c2-47a7-9f96-06facb4a7d99.png)
