### ISSUE TITLE
Custom block tag scope

### ISSUE THREAD

**Issue by dsbudiac** [harttle/liquidjs#40]
I'm trying to create a custom block tag like so:

**main.liquid**
```liquid
{% carousel %}Carousel #1{% endcarousel %}
```

**carousel.liquid**
```liquid
<div class="carousel">{% content %}</div>
```

Rendering `main.liquid`, should replace `{% content %}` with whatever is inside the carousel tags. In the example above it'd create:

**result.html**
```html
<div class="carousel">Carousel #1</div>
```

I've coded tag registration like so:

```js
engine.registerTag('content', { render: async () => '' });
engine.registerTag('carousel', {
  parse: (token, remainingTokens) => {

    let stream = engine.parser.parseStream(remainingTokens);
    this.tokens = [];

    stream
      .on('template', token => this.tokens.push(token))
      .on(`tag:endcarousel`, () => stream.stop())
      .on('end', () => { throw new Error(`tag ${token.raw} not closed`); });

    stream.start();
  },
  render: async (scope, hash) => {

    let innerTokens = this.tokens;
    let outerTokens = await engine.getTemplate('carousel');
    let result = [];

    for (let i = 0; i < outerTokens.length; i++) {
      let token = outerTokens[i];
      if (token.name === 'content') {
        Array.prototype.push.apply(result, innerTokens);
      } else {
        result.push(token);
      }
    }

    return await engine.renderer.renderTemplates(result, scope);
  }
});
```

The above code works _until there are multiple `{% carousel %}` blocks on a template_. In which case it'll just _repeat the contents of the last defined_ carousel.

This tells me I have a block/scoping issue, and am perhaps not registering blocks/tokens correctly. Can somebody point me in the right direction? I've looked at how the `layout` and `include` tags are registered, but not sure I grasp what I need to do.

**Comment by harttle** [comment]
Your tags seem to be registered correctly. I cannot reproduce your problem with [this gist](https://gist.github.com/harttle/0c38373b1c755ebf804c9889fd08cb73). It works well with only one `{% carousel %}` block.

**Comment by dsbudiac** [comment]
Yea, I can get the tag block to **work fine with only one** `{% carousel %}`.

The problem is when I introduce multiple `{% carousel %}` elements in a given template. When I have multiple, the **contents of the last block element will just be repeated for all previous** `{% carousel %}` tags.

I [forked your gist](https://gist.github.com/dsbudiac/8dbcdf0f4a4dac9d61588fff4c86e6ff) to illustrate. Output will just repeat `Carousel #2`.

**Expected output:**

```html
<div class="carousel">Carousel #1</div><div class="carousel">Carousel #2</div>
```

**Actual output:**

```html
<div class="carousel">Carousel #2</div><div class="carousel">Carousel #2</div>
```

**Comment by dsbudiac** [comment]
Nevermind. As I suspected, it was an issue `this` scoping. Just can't use anonymous functions.

[This gist](https://gist.github.com/dsbudiac/9c92d7ccf3cb5afd5797d1ec8d267c10) shows the fix

**Comment by harttle** [comment]
There's no binding of this when using arrow function, see: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions>
I didn't spot it, either, LOL
