### ISSUE TITLE
Files without extensions should not always get the .liquid extension

### ISSUE THREAD

**Issue by ilg-ul** [harttle/liquidjs#41]
I encountered a small problem with the file names.

In my project I have templates for files with various content (C/C++, JSON, markdown, XML).

To help Eclipse select the right editor, I kept the original file extension, and inserted `-liquid` before the extension.

With this rule, my files are named like `initialize-liquid.c`, `package-liquid.json` etc.

However, when I tried to use a file named `LICENSE-liquid`, I got some errors claiming that the file is not found. I had no time to investigate, I renamed the file to `LICENSE.liquid` and avoided the problem.

My understanding was that the parser did not actually check if the file is present, but was directly upset by the missing extension, tried to add the default `.liquid`, and failed.

Could you check if this is true? If so, is this really the desired behaviour? I don't see any reasons why files without extnsions should not be accepted; if they exist they are as good as any other files.

**Comment by harttle** [comment]
Setting `extname` to `""` will work for you :)

**Comment by ilg-ul** [comment]
> Setting `extname=""`
 
ugly :-(

in the mean time I had to switch to your naming scheme, so this should no longer be a problem for me.
