### ISSUE TITLE
Abstract file system. Wrong root passed to resolve

### ISSUE THREAD

**Issue by floofnoodlecode** [harttle/liquidjs#412]
I am using liquidjs in a react app, so it is running in the browser. I need to customize how the paths are interpreted, so I provided an FS object like in the [documentation](https://liquidjs.com/tutorials/render-file.html). I also need to change the default root.

The issue is that the root that gets passed to `resolve(root, file, ext)` is not the one that I'm providing when creating the Liquid instance. I end up with a URL as `root`. I spent some time debugging this. Take this code for example:

```javascript
const engine = new Liquid({
  fs: some_fs_implementation,
  root: '~',
})
```

When creating a new Liquid object, the options are first normalized using `src/liquid-options.ts: normalize()`, which calls `normalizeDirectoryList(options.root)`. This function returns:
``` javascript
  return list.map(str => fs.resolve(str, '.', '')).map(str => str[str.length - 1] !== '/' ? str + '/' : str)
```
However, the `fs.resolve()` that this function uses is not the `fs` that I passed in the options. Not only that but it also adds other characters after the root I provided.

I don't understand why that return is the way it is, but it seems to behave in a really unintuitive way.

**Comment by harttle** [comment]
You're right. Both of the two ideas.
