### ISSUE TITLE
Templates imported by `{% render %}` not cached for concurrent async render

### ISSUE THREAD

**Issue by floofnoodlecode** [harttle/liquidjs#416]
The documentation states that caching is performed when you call `renderFile()` .  I am using `parseAndRender()` instead, so I don't expect the initial template to get cached. However, the template that I am rendering uses a render tag `{% render "template.liquid" %}`. If I render the original template multiple times, is `template.liquid` cached?

As liquid options, I am passing `{cache:true, fs: customFS}` and I can see that `customFS.readFile()` gets called multiple times for that same `template.liquid` file. Is this the expected behavior?

**Comment by harttle** [comment]
I finally figured out that it's because cache is written when async `parseFile` complete, the following snippet works:

```javascript
const liquidjs = require('../liquidjs')

const engine = new liquidjs.Liquid({
	cache: true,
	extname: '.liquid',
	root: '~',
	fs: {
		exists: async (filepath) => {console.log(`exists()`); return true},
		resolve: (root, file, ext) => root + '#' + file + ext,
		sep: '#',
		readFile: async (filepath) => {console.log(`readFile()`); return 'HELLO'}
	}
})

async function main() {
	for (let i = 0; i < 5; i++) {
                // readFile() logged only once
		await engine.parseAndRender("{% render 'template' %}").then(console.log)
	}
}

main()
```

Anyway it's a bug not caching ongoing parse. Will be fixed soon.

**Comment by Nukeshepard86** [comment]
> Here is an example:
> ```javascript
> const liquidjs = require('liquidjs')
> 
> const engine = new liquidjs.Liquid({
> 	cache: true,
> 	extname: '.liquid',
> 	root: '~',
> 	fs: {
> 		exists: async (filepath) => {console.log(`exists()`); return true},
> 		resolve: (root, file, ext) => root + file + ext,
> 		readFile: async (filepath) => {console.log(`readFile()`); return 'HELLO'}
> 	}
> })
> 
> for (let i = 0; i < 5; i++) {
> 	engine.parseAndRender("{% render 'template' %}").then(console.log)
> }
> ```
> 
> Console output:
> ```
> exists()
> exists()
> exists()
> exists()
> exists()
> readFile()
> readFile()
> readFile()
> readFile()
> readFile()
> HELLO
> HELLO
> HELLO
> HELLO
> HELLO
> ```
> 
> I would expect both `exists()` and `readFile()` to be called only once.
