### ISSUE TITLE
Iterating a hash

### ISSUE THREAD

**Issue by thehappybug** [harttle/liquidjs#42]
Hello

I have been trying to iterate a hash/object in Liquid but the output is not as expected.

See Liquid reference: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#allowed-collection-types

The reference says:

> When iterating a hash, item[0] contains the key, and item[1] contains the value:

```liquid
{% for item in hash %}
  {{ item[0] }}: {{ item[1] }}
{% endfor %}
```

However, `item[0]` and `item[1]` contain the first and second characters of the item key instead of having the key and the value of current item.

Am I iterating the hash correctly? Is this a not-implemented feature?

PS: Thank you for the work on liquidjs. Its awesome. 😃

**Comment by harttle** [comment]
Fixed by #43
