### ISSUE TITLE
Setting globals dynamically after opts argument removed from renderFile()

### ISSUE THREAD

**Issue by PlanetIrata** [harttle/liquidjs#432]
Hi

I juste upgraded my app from LiquidJS 9.25.1 to the latest 9.28.6

I am facing bugs and just find that the `opts`parameter of `renderFile` has been removed in version [9.26.0](https://github.com/harttle/liquidjs/compare/v9.25.1...v9.26.0) :

```typescript
public async renderFile (file: string, ctx?: object, opts?: LiquidOptions) {
     const templates = await this.parseFile(file, opts)
     return this.render(templates, ctx, opts)
}
```

My app was using this parameter to pass a customized `globals` setting to the rendered file (depending on the file, this is why I don't set the `globals` setting while creating the engine). 

Is there another way to do this without re-creating an engine before each call to `renderFile` ?

P.S. as stated in #395 this should have been flagged as a breaking change in 9.26.0

**Comment by PlanetIrata** [comment]
My problem is to find a way to modify `globals` dynamically after the creation of the engine (without recreating it). 

The `renderFile` function allowed this prior to version 9.26.0

Thanks for your help!

**Comment by harttle** [comment]
I think it makes sense to provide a render specific options when calling `.render()`, try v9.29.0 with following:

```typescript
const globals = {}  // the globals you need to set for this render call
engine.render(<file>, {}, {globals})
```

**Comment by amit777** [comment]
This is fortuitous because I was looking to do something like this as well.   It seems to work for me. Thanks!

**Comment by amit777** [comment]
just an FYI.  The reason we need this is each customer has different global settings.  Currently, we create one engine object per customer which seems wasteful.  Being able to pass in customer-specific globals into the render function will allow us to not have to create a liquid engine for each customer!

**Comment by PlanetIrata** [comment]
> Hey @PlanetIrata, I think it makes sense to provide render specific options when calling `.render()`, try v9.29.0 with following:
> 
> ```ts
> const globals = {}  // the globals you need to set for this render call
> engine.render(<file>, {}, {globals})
> ```
> 
> Feel free to post back if there's more problems on this, or that doesn't work for you. Please see this doc for details: https://liquidjs.com/api/classes/liquid_.liquid.html#renderFile

Hi @harttle 

Seems to work perfectly with 9.29.0 

Thanks!
