### ISSUE TITLE
Implement `allow_false` argument in `default` filter

### ISSUE THREAD

**Issue by sebastienros** [harttle/liquidjs#435]
https://shopify.github.io/liquid/filters/default/#allowing-false

**Comment by harttle** [comment]
[Truthy and Falsy](https://liquidjs.com/tutorials/truthy-and-falsy.html) in LiquidJS is mostly aligned with shopify liquid. So I guess this feature is also compatible and good to have.

**Comment by harttle** [comment]
Try [v9.32.0](https://github.com/harttle/liquidjs/releases/tag/v9.32.0)
