### ISSUE TITLE
Should smartquotes fail parsing?

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#446]
I notice that the `{% assign foo = “bar” %}` parses correctly even though it should be `{% assign foo = "bar" %}` (notice the small difference in the quotation marks).     The template parses fine, but I feel like it should probably throw a parsing error since the quotes are not regular quotes.  What do you think?

**Comment by harttle** [comment]
I agree with you! Maybe change `this.value = tokenizer.remaining()` to `tokenizer.readValue()` can solve this.

**Comment by harttle** [comment]
I noticed it cannot repro here:
https://liquidjs.com/zh-cn/playground.html#eyUgYXNzaWduIGZvbyA9IOKAnGJhcuKAnSV9Cnt7YmFyfX0=,e30=
