### ISSUE TITLE
Offer a renderSync method?

### ISSUE THREAD

**Issue by zachleat** [harttle/liquidjs#48]
Most templating engines offer synchronous render methods (ejs, mustache, handlebars, haml, pug, nunjucks, etc).

Does one exist for liquidjs? If not, could one be added?

(love this library btw—thank you)

**Comment by harttle** [comment]
Maybe not possible current code base. We know async interface cannot be converted to sync. So we made intensive discussion over whether to support async in #3 .

Nevertheless, supporting sync render methods without regression would be great. Welcome to propose a solution for this issue.

**Comment by zachleat** [comment]
Interesting! To be frank I think I’d be happy with throwing an error if the template has an async tag and rendering is in sync mode.

**Comment by zachleat** [comment]
I worked around this in my upstream code so it isn’t necessary for me any more! It may be useful for someone else in the future but I would consider it low priority. In fact, other libs might tend towards what you’ve done instead 😎 Thanks for the discussion!

**Comment by harttle** [comment]
Now we use TypeScript and I'll try make it support both async and sync calls, maybe generate additional code during rollup build.

**Comment by harttle** [comment]
`renderFileSync`, `renderSync`, `parseAndRenderSync` are now supported by v9.0.0, but with some breaking changes. Feel free to file an issue if there's problem during upgrade. Closing, hope it helps!

**Comment by Munawwar** [comment]
Ok I did a simple test of `renderSync()` and seems to be working. Integrated liquidjs with SahteReact (front-end library I was building for Shopify stores... so now, one can reuse shopify templates on the client-side co-existing with libraries like jquery!)

https://github.com/Munawwar/SahteReact/commit/3251a213553e1ce719a0a36f3cd97e91cfa745a5

@harttle how to `include` partials on browser (without async fetching)? how to use `dynamicPartials`?

**Comment by harttle** [comment]
By default, it's implemented as sync xhr  which is absolutely bad practice. see:

https://github.com/harttle/liquidjs/blob/f661cd8b858fa897e595978bcb1eafb1137ee357/src/fs/browser.ts#L47 , 

A customed, platform-related `fs` can be specified in the [LiquidOptions](https://harttle.land/liquidjs/interfaces/_liquid_options_.liquidoptions.html#fs), as discussed in #131
