### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by ricdikulous** [harttle/liquidjs#49]
Hey mate I was wondering if it is possible to use strings such as `2016-01-05T13:15:23` with the date filter or does it only support JS date objects?

**Comment by harttle** [comment]
The [date filter](https://github.com/harttle/liquidjs/blob/master/filters.js#L26-L29) only support `Date` and `"now"` currently. It sounds good to support a string as the `Date` construction parameter.

**Comment by harttle** [comment]
Now it's supported @2.1.0, see test cases [here](https://github.com/harttle/liquidjs/blob/master/test/filters.js#L87-L102)
