### ISSUE TITLE
Automatic output escaping

### ISSUE THREAD

**Issue by floofnoodlecode** [harttle/liquidjs#500]
Hello,

As far as I understand, there is no auto-escape mechanism built into liquidjs. Would it be possible to provide an option that would enable auto-escaping of any output rendered by `{{ value }}`?

My use case is that users will write .liquid templates for rendering HTML, JSON, etc. Requiring the users to make sure that every single output is escaped properly (e.g. `{{ x | escape}}` for HTML, or `{{ x | json}}` for JSON) is tedious and confusing.

Would you be willing to add an option that takes a function which will be applied on every output? (e.g. `{autoEscape: (val: any) => any}`)

**Comment by harttle** [comment]
Makes sense. This option makes templates safer.

**Comment by harttle** [comment]
Now it's supported on v9.37.0. I created some test cases here: https://github.com/harttle/liquidjs/blob/f88490cd3cd0b5316c43c3ca76837544d99ce0b0/test/integration/liquid/outputEscape.ts#L4-L42

**Comment by floofnoodlecode** [comment]
This is such great news. Thank you very much.

This will be so much cleaner than my hack. I wasn't expecting you to add this feature so soon so I registered a tag that would add the "| escape" filter to all output tokens. 😂 

By the way, one observation regarding the docs: https://liquidjs.com/tutorials/parse-parameters.html

The docs instruct to create a new tokenizer like so: `const tokenizer = new Tokenizer(tagToken.args)`.
However, typescript complains that 2-3 args are needed. I saw that in your code you actually use this: `const tokenizer = new Tokenizer(token.args, this.liquid.options.operatorsTrie)`

**Comment by rauschma** [comment]
One option would be to do what Handlebars does:

* `{{expression}}` escapes `expression` before inserting it.
  * By default, escaping is for HTML, but users can provide their own escape function.
* `{{{expression}}}` inserts unescaped/raw.

Source: https://handlebarsjs.com/guide/expressions.html
