### ISSUE TITLE
Any way to log or see what values is the given template using from the given scope/context?

### ISSUE THREAD

**Issue by bediu** [harttle/liquidjs#507]
I have a rather big scope that I pass per template. Not every template uses the same variables.

For example: 
```javascript
var data_object = {
    companyName: 'Acme',
    author: 'bediu'
}

var my_author_template = `
<h2>
    
    {% assign var1 = author %}
    {% assign var2 = var1 %}
    {% assign var3 = var2 %}

    {{var3}}
</h2>
`;

console.log(liquidEngine.parseAndRenderSync(my_author_template, data_object);
```

Is there a way to know that this template is accessing `author` from the given scope?  

I've been reading the docs and there isn't necessarily an option for it, but maybe by guiding me in the source code?  I use the node version.

**Comment by harttle** [comment]
duplicate with #496, please refer to that discussion and post comments there.
