### ISSUE TITLE
Parsing array broke in `9.36`

### ISSUE THREAD

**Issue by neverether** [harttle/liquidjs#508]
Upgrading from `9.35` to `9.36`, I get an error parsing this:

`{{\"$1円（$2）\" | edit: [\"\", service_fee, service_tax]}}`

I get the error `Unexpected character "]"` – potentially related to this commit here? https://github.com/harttle/liquidjs/commit/049685b9a0271ba03875e24ff2f6c7870cae62a7

**Comment by harttle** [comment]
Thank you for digging into this. I believe it's caused by this commit which is intended to raise error for malformed template:

```diff
diff --git a/src/parser/tokenizer.ts b/src/parser/tokenizer.ts
index f0399c1a..621f9000 100644
--- a/src/parser/tokenizer.ts
+++ b/src/parser/tokenizer.ts
@@ -89,7 +89,8 @@ export class Tokenizer {
         ++this.p
         const arg = this.readFilterArg()
         arg && args.push(arg)
-        while (this.p < this.N && this.peek() !== ',' && this.peek() !== '|') ++this.p
+        this.skipBlank()
+        assert(this.end() || this.peek() === ',' || this.peek() === '|', () => `unexpected character ${this.snapshot()}`)
       } while (this.peek() === ',')
     }
     return new FilterToken(name.getText(), args, this.input, begin, this.p, this.file)
```

So I assume the filter arguments should not be wrapped in `[]`:

```liquid
{{"$1円（$2）" | edit: service_fee, service_tax }}
```

I don't know Liquid has such a syntax to pass arguments in `[]`, please correct me if I'm wrong.

**Comment by neverether** [comment]
Thanks for digging deeper. To be completely honest, my familiarity with Liquid isn't super high, and after trying to find documentation around array syntax in Liquid, I actually can't find much at all. It might be likely that it's not actually part of the Liquid spec as you suspect.

I'll see if our teams' implementation will work without wrapping in `[]`
