### ISSUE TITLE
Includes and String requirement on Paths

### ISSUE THREAD

**Issue by zachleat** [harttle/liquidjs#51]
(Love this library—thank you!)

This is going to be a very specific nitpick so just keep that in mind. I wanted to use this lib to parse some existing Jekyll templates and while I don’t expect a completely fluid parse, one thing that did trip me up: Jekyll includes.

Specifically, Jekyll uses `{% include footer.html %}` (without quotes) and this library expects `{% include 'footer.html' %}` (quotes). I suppose I just have a question: is this a limitation of the library (something that could be worked around) or a limitation of any non-Ruby implementation?

Thanks!
Zach

**Comment by harttle** [comment]
This is a intended in liquidjs, to support dynamic including.

All built-in tags can be override by register a new Tag, you can simply write your `include`. But I'm thinking about support this by some kind of options, like `{include: 'static'}`. What do you think?

**Comment by harttle** [comment]
Published @ 2.2.0. Setting `dynamicPartials` to false enables this feature.

**Comment by zachleat** [comment]
Oh, wow! Amazing—thank you!!
