### ISSUE TITLE
`@` fails to compile

### ISSUE THREAD

**Issue by mehulkar** [harttle/liquidjs#510]
liquid fails to parse strings that have an `@` in them. It used to work in v6. Working on tracing what changed since then. 

Repro: https://github.com/mehulkar/repro-liquidjs-hbs

This issue fails upstream in 11ty: https://github.com/11ty/eleventy/issues/2434

**Comment by harttle** [comment]
`@` in ruby is used to create a class instance, while in Liquid templating, I'm not sure whether it's a valid variable name. Please advice if you know better.

Here's what I got in Liquid (the ruby version):

```ruby
scope = {
  "str" => "string",
  "@str" => "at string",
}

template = <<-EOF
{{ str }}
{{ @str }}
EOF

puts Liquid::Template.parse(template).render!(scope)
```

Output:

```
string
string
```

**Comment by harttle** [comment]
Closing as the `@` syntax is not intended to be parsed by Liquid in the downstream case.

For anyone find identifier name parsing is not compatible with shopify/liquid please open another issue, for ones think we need a more tolerable parser, please open a discussion.
