### ISSUE TITLE
for tag does not support valueOf recognition in Drop

### ISSUE THREAD

**Issue by maiyuanrdt** [harttle/liquidjs#515]
Shopify Code example:
```html
<ul> 
  {%- for field in form.errors -%}
    <li>
      {%- if field == 'form' -%}
        {{ form.errors.messages[field] }}
      {%- else -%}
        <a href="#RegisterForm-{{ field }}">
          {{ form.errors.translated_fields[field] | capitalize }}
          {{ form.errors.messages[field] }}
        </a>
      {%- endif -%}
    </li>
  {%- endfor -%}
</ul>
```
The above is the liquid code structure that outputs the error information in the form form in Shopify, in which for is used to traverse form.errors and use it as an index key.
The result of execution in Shopify is:
![origin_img_v2_ac6c3940-e11b-42e2-b06f-03de03104deg](https://user-images.githubusercontent.com/88075366/177267162-c5bc9bcc-1f49-4117-8895-b1e6f588d717.jpg)
and
![origin_img_v2_a4e5db1d-0d8a-43cb-b204-320769d92d8g](https://user-images.githubusercontent.com/88075366/177267198-0c8599b5-229d-46dc-a658-9240ebc01a67.jpg)

-------------------------------------------------------------problem lies in------------------------------------------------------------
Using liquidjs for simulation adaptation, it was found that the valueOf in Drop was not responded to.
```javascript
class ErrorsDrop extends Drop {
    constructor() {
        super()
        this.password = 'pppp'
        this.email = 'eeee'
    }

    valueOf() {
        return ['xxx', 'ccc']
    }
}
const errors = new ErrorsDrop()
liquid.parseAndRender('-- This {{ name }}: {{errors}} -- {% for field in errors %} ={{ field }}= {% endfor %}', {
    name: 'valueOf',
    errors
})
```
I defined an object named ErrorsDrop, assigned it to the errors variable, and traversed the errors through the for tag, and got the following results:
```
-- This valueOf: xxxccc --  =passwordpppp=  =emaileeee= 
```
Personally think that when for in is followed by a Drop object, it should respond to the result after its valueOf(). Otherwise, writing similar to Shopify will not take effect

**Comment by harttle** [comment]
Try adding json filter as you’re in Shopify template 

```liquid
This {{ name }}: {{errors|json}} -- {% for field in errors %} ={{ field|json }}= {% endfor %}', {
    name: 'valueOf',
```

The way LiquidJS iterate objects can be different. I can try fix it as a bug.

**Comment by harttle** [comment]
Try v9.39.0, maybe you're interested in this:

https://github.com/harttle/liquidjs/blob/4289b4e8048fc08963ae1a9d526920ec221c1c69/test/integration/builtin/tags/for.ts#L321-L330

Note that if you decide to use `valueOf`, you'll have to implement the `Symbole.iterator` on the return value of `valueOf`.
