### ISSUE TITLE
Comments should be skipped

### ISSUE THREAD

**Issue by aleclarson** [harttle/liquidjs#53]
Currently, comments are not ignored. Is that the ideal behavior in your opinion, @harttle?

**Comment by harttle** [comment]
Do you mean `{% comment %}` tag? It seems OK in unit tests: https://github.com/harttle/liquidjs/blob/master/test/tags/comment.js

I'll add more test cases for it.

**Comment by aleclarson** [comment]
I mean HTML comments: `<!-- <div class="{{ foo }}"></div> -->`

It might be best for Liquid to avoid parsing tokens there.

**Comment by harttle** [comment]
By design, template engines like liquid will not parse HTML, and can be used for common purposes, like generating C++ code as mentioned by #19.
I tried out the original [shopify/liquid](https://github.com/shopify/liquid), tags in HTML comments are always rendered.

**Comment by harttle** [comment]
As for commenting out template code, I suggest editor plugins like [atom liquid language](https://atom.io/packages/language-liquid), [liquid mode for sublime](https://github.com/siteleaf/liquid-syntax-mode)
