### ISSUE TITLE
custom token definitions?

### ISSUE THREAD

**Issue by icai** [harttle/liquidjs#54]
I want to use part of front end template and use  part of back end template.
so catch the token definition rended!
open {{
close }}

I want to chang to
open: '<%=',
close: '%>'

----
or use raw block to render?

**Comment by harttle** [comment]
It'll be a useful feature.

Most (if not all) lexical parsing is located at `src/tokenizer.js`, it should be easy to provide options to re-define syntax for outputs and tags. PR is wellcome, I can help make it running.
