### ISSUE TITLE
Better feature to develop! The Template need to have a method render instead of using global  engine to render.

### ISSUE THREAD

**Issue by smil4ever** [harttle/liquidjs#551]
Just need the template compile form a file or string, and then we can use the compiled template anywhere, template self render directly!

**Comment by harttle** [comment]
As there's no further discussion on this topic, closing as by-design. This design cannot be easily changed as it's not backward compatible. But anyone interested in this feature can use following snippet:

```javascript
const liquid = new Liquid()
function parse(template) {
    const tpls = liquid.parse(template)
    return function render(scope) {
        return liquid.render(tpls, scope)
    }
}
```
