### ISSUE TITLE
setting timezone for specific template

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#553]
Hi, we have a need to be able to set the timezone for the date filter defined here: https://liquidjs.com/filters/date.html

Is it possible to update the `date` filter to have an optional second parameter of the timezone?

eg: `{{ article.published_at | date: "%a, %b %d, %y":"America/Los_Angeles" }}`

I didn't quite understand the note in the documentation about how to set the timezon in liquid options.

**Comment by amit777** [comment]
From what I can tell, the current option is to set the timezone for the whole rendering engine.  Unfortunately this won't work for our use-case as different templates need to be able to render dates in different timezones.

**Comment by harttle** [comment]
Thank you @amit777 , the docs for `timezoneOffset` surely need to be elaborated with more details. Basically it's used to specify a timezone offset globally (setting to 0 means UTC).

Along with that, I think we can support a `timezone` for each `date` call as well. While I don't want to include and maintain a timezone database inside liquidjs, we need make use of [JavaScript Data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) whenever we can. Maybe use the same format to specify a timezone as in `new Date`.

**Comment by amit777** [comment]
I'm open to anything. We have users who have different time zone setting, so the global option is problematic for us.

**Comment by harttle** [comment]
I find timezone string like `America/Los_Angeles` is only supported in `toLocaleDateString()`, and cannot be converted to timezone offset for use of strftime. So I supported specifying a timezone offset for now. Still looking for better options.

timezoneoffset is defined as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

```
// 360 is for -06:00 timezone
{{ "1990-12-31T23:00:00Z" | date: "%Y-%m-%dT%H:%M:%S", 360}}
```

**Comment by amit777** [comment]
Maybe this can be a optional filter that depends on extranal modules? Like a liquidjs extras repo?

**Comment by harttle** [comment]
I came across a stackoverflow and find it's possible to support names, now can be used like

```liquid
{{ "2021-01-01T23:00:00Z" | date: "%Y-%m-%dT%H:%M:%S", "America/New_York" }}
```

Note: it can be tricky for date literals when DST is active. It can be viewed as 2 steps

1. use the specified date (literal or from scope) to determine whether DST is active
2. determine timezone offset depending on whether DST is active
3. call strftime with this offset

**Comment by amit777** [comment]
Hi there.. sorry to comment on closed issue.  But it looks like the documentation on https://liquidjs.com/filters/date.html should be updated to include the new TimeZone parameter.
