### ISSUE TITLE
Feature:  filter to add query string parameters

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#555]
It would be awesome to have a filter that could add parameters to a URL and automatically handle adding the `?` to the URL if a parameter doesn't exist on the URL as well as overwrite the parameter if it already exists. Also handle hashes in the url as well.

eg
```
{{ "https://example.com" | append_query: "utm_source", "email" }}
```
output:
```
https://example.com?utm_source=email
```

**Comment by pdehaan** [comment]
@amit777 Maybe something like this?

```js
const { Liquid } = require("liquidjs");
const engine = new Liquid();
engine.registerFilter('append_query', (url, name, value) => {
  const _url = new URL(url);
  _url.searchParams.append(name, value);
  return _url.href;
});

const tpl = engine.parse('{{ "https://example.com" | append_query: "utm_source", "email" }}');
engine.render(tpl)
  .then(console.log); // "https://example.com/?utm_source=email"
```

**Comment by amit777** [comment]
Thanks! I'll give it a shot!

**Comment by amit777** [comment]
works like a charm!

**Comment by pdehaan** [comment]
Another option I kind of like:
```js
function (url, query="") {
    const _url = new URL(url);
    const _query = new URLSearchParams(query);
    for (const [k, v] of _query.entries()) {
      _url.searchParams.append(k, v);
    }
    return _url.href;
  }
```

```liquid
{{ "https://example.com?name=peter" | append_query: "utm_source=email&foo=bar&name=paul" }}
```

### OUTPUT
`https://example.com/?name=peter&utm_source=email&foo=bar&name=paul`

Feels a bit easier to chain multiple query params together without passing objects (and parsing as a URLSearchParams query string). Plus seems to append query params decently; although doesn't dedupe them as seen above.
