### ISSUE TITLE
9.42 introduces bug with evalToken

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#556]
this code works fine with 9.41.0.  It outputs `random:John`  I've copied from the tutorial at https://liquidjs.com/tutorials/parse-parameters.html:
```js
const { Liquid, Tokenizer, evalToken } = require('liquidjs')
const liquid = new Liquid({jsTruthy: true});
liquid.registerTag('random', {
  parse: function (tagToken) {
    const tokenizer = new Tokenizer(tagToken.args)
    this.items = []
    while (!tokenizer.end()) {
      this.items.push(tokenizer.readValue())
    }
  },
  render: async function(context, emitter) {
    const index = Math.floor(this.items.length * Math.random())
    const token = this.items[index]
    const value = await evalToken(token, context)
   // in our code, we await some async functions that are passed in via the global context   

    // in our code we actually just return the value rather than do emitter.write
    emitter.write(value)
  }
});

let tpl = `random:{% random "bar" "foo" obj.name  %}`
let context = { obj: {name: 'John'}};

setTimeout(async function() {
  let template = await liquid.parse(tpl);
  let ret = await liquid.render(template, context);
  console.log(ret);
})
```

with 9.42.0 and 9.42.1, the output is `random:[object Object]`

**Comment by amit777** [comment]
so it looks like evalToken started to return an iterator in 9.42.0 rather than the token value.  I see some mention that `evalToken()` is deprecated.. and I see some use for `_evalToken()`, but it's not clear why this is changed.

**Comment by amit777** [comment]
also, a side note, we have created custom liquidjs tags that call async functions.  This is why our `render` is an async function.

**Comment by amit777** [comment]
ok. I'm being dumb.  In case anyone else comes across this, the documentation has explanation of generators and async functions. https://liquidjs.com/tutorials/sync-and-async.html

**Comment by harttle** [comment]
> so it looks like evalToken started to return an iterator in 9.42.0 rather than the token value. I see some mention that `evalToken()` is deprecated.. and I see some use for `_evalToken()`, but it's not clear why this is changed.

Yes, it's a LiquidJS specific way of programming, a simple way to implement for both sync and async calls. I added `_` prefix for all LiquidJS-async APIs. Glad you find that doc.
