### ISSUE TITLE
Case/When should evaluate multiple When statements

### ISSUE THREAD

**Issue by sebastienros** [harttle/liquidjs#559]
```
{% assign tag = 'Love' %}

{% case tag %}
  {% when 'Love' or 'Luck' %}
    This is a love or luck potion.
  {% when 'Strength','Health', 'Love' %}
    This is a strength or health or love potion.
  {% else %}
    This is a potion.
{% endcase %}
```

Should display both statements.
https://shopify.dev/api/liquid/tags/case
https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/case.rb#L73-L87

**Comment by harttle** [comment]
Fixed in version 10.2, see https://github.com/harttle/liquidjs/commit/d17813ef5217264bd08f741b0e1f713bedf2d464
