### ISSUE TITLE
assign variable scope doesn't include loops

### ISSUE THREAD

**Issue by larrykluger** [harttle/liquidjs#56]
Hi,
Thank you for your time on the library. 

A bug:

````
{% assign total = 10 %}
{% for line in (0..2) %}
    {% assign total = 20 %}
{% endfor %}
Total: {{total}} -- should be 20<br>
````
shows 10 as the result, this is a bug.

The [live dot liquid](http://dotliquidmarkup.org/try-online) site correctly shows 20.

Thanks,
Larry

**Comment by harttle** [comment]
In the current implementation, tags like `for`, `include` create new scopes, thus `assign`s within it cannot be accessed outside.
Since one of the principles of this repo is being compliant with [shopify/liquid](https://github.com/shopify/liquid), I'll have a look at the ruby version.

**Comment by larrykluger** [comment]
This repo, `liquidjs`,  **does** handle this issue correctly. 

But your npm release `shopify-liquid` has the bug. 

Is npm `shopify-liquid` obsolete?

(I wanted to raise the issue with the `shopify-liquid` package. I didn't notice that the Github link on the NPM page for shopify-liquid led me here...)

**Comment by harttle** [comment]
> Is npm `shopify-liquid` obsolete?

Yes, when upgrading to the latest version of `shopify-liquid`, you'll get a warning message saying this `shopify-liquid` is renamed to `liquidjs`.

Liquidjs is almost backward-compatible, changes including whitespace control (#17), and falsy values (#26).

These changes make liquidjs more compatible to the ruby version as used in jekyll. I recommend upgrade to `liquidjs`. If you have problems doing so, please let me know.
