### ISSUE TITLE
Custom tag registration doesn't work in Liquid v10

### ISSUE THREAD

**Issue by oscarotero** [harttle/liquidjs#568]
Hi.
In Liquidjs v9 I have the following code to create custom tags:

```js
engine.registerTag('upper', {
  parse: function(tagToken, remainTokens) {
      this.str = tagToken.args;
  },
  render: async function(ctx) {
      const str = await this.liquid.evalValue(this.str, ctx);
      return str.toUpperCase();
  }
});
```

This code fails in Liquid 10: `Uncaught RenderError: Cannot read properties of undefined (reading 'toUpperCase')`.

I found [this example in the documentation](https://liquidjs.com/tutorials/register-filters-tags.html#Register-Tags) but it doesn't work either:

```js
engine.registerTag('upper', {
    parse: function(tagToken) {
        this.str = tagToken.args; // name
    },
    render: function*(ctx) {
        const str = yield this.liquid.evalValue(this.str, ctx);
        return str.toUpperCase()
    }
});
```

**Comment by harttle** [comment]
I didn't realize `evalValue` is advocated in docs and demos. I removed support for `Context` as second parameter when dealing with #527 because it's not used my source code. Now added it back because I think it's indeed convenient (so I used it in my docs).

Performance-wise, it's better to create `new Value()` during `parse`, and call `value.value()` in `render()`. As in the implementation of builtin tags.

**Comment by oscarotero** [comment]
Thanks for the fast response.

> Performance-wise, it's better to create new Value() during parse, and call value.value() in render(). As in the implementation of builtin tags.

I don't have any preference, so if it's more perfomant this suggestion, I'll change it. Can you provide an example for that (or update the example in the documentation)? Somethig like this:

```js
engine.registerTag('upper', {
  parse: function(tagToken, remainTokens) {
      this.val = new Value(tagToken.args);
  },
  render: async function(ctx) {
      const str = this.val.value();
      return str.toUpperCase();
  }
});
```

**Comment by harttle** [comment]
Updated this tutorial: https://liquidjs.com/tutorials/sync-and-async.html Hope it helps!

**Comment by oscarotero** [comment]
Perfect. Thanks!
