### ISSUE TITLE
How to rewrite a registerTag from v9 to be v10 compatible?

### ISSUE THREAD

**Issue by HenrikPoulsen** [harttle/liquidjs#570]
in v9 I have the followin registerTag:
```js
engine.registerTag('metadata_file', {
  parse(tagToken: TagToken, remainTokens: TopLevelToken[]) {
    this.str = tagToken.args;
  },
  async render(ctx: Context) {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    const content = await readLocalFile(this.str);
    return this.liquid.parseAndRender(content.toString(), ctx);
  },
});
```
Upgrading to v10 causes this to fail since `str` has been removed.
In the docs [here](https://liquidjs.com/tutorials/register-filters-tags.html) it says to use the following:
```js
engine.registerTag('upper', {
    parse: function(tagToken: TagToken, remainTokens: TopLevelToken[]) {
        this.value = new Value(token.args, liquid)
    },
    render: function*(ctx: Context) {
        const str = yield this.value.value(ctx); // 'alice'
        return str.toUpperCase() // 'ALICE'
    }
});
```
However it complains that `value` does not exist on `Tag`, that `token` cannot be found as well as that `liquid` cannot be found.
So presumably the samples are incorrect. I am trying to update to liquidjs `10.3.2`.

**Comment by harttle** [comment]
Yeah the type is broken, previously it sets `this` to `[key: string]: any`, now applying it back.

Another problem is `parseAndRender` doesn't support a `Context` in recent versions. I'm also adding this support back to allow plain object OR `Context` as a scope.

**Comment by harttle** [comment]
I added this case and it now works for me, please check v10.3.3

https://github.com/harttle/liquidjs/blob/fb6a9f8717cd57522d53687da7e4718b28a7f68a/test/e2e/issues.ts#L349-L364

**Comment by HenrikPoulsen** [comment]
I have tried the new version and it works perfectly with my existing code. Thanks!
