### ISSUE TITLE
Add support for passing LiquidOptions from CLI

### ISSUE THREAD

**Issue by DaRosenberg** [harttle/liquidjs#583]
It would be very useful to be able to pass [options](https://liquidjs.com/tutorials/options.html) from the CLI, for example:

```
cat template.liquid | npx liquidjs --jsTruthy=true '{"name": "Snake"}'
```

If idea is supported by maintainers, I will contribute this as a PR.

**Comment by harttle** [comment]
I'm glad that finally we have a CLI related issue. It makes sense to allow passing options. I can help review and publish your change.
