### ISSUE TITLE
CLI should take context from stdin and template from arg (instead of the other way around)

### ISSUE THREAD

**Issue by DaRosenberg** [harttle/liquidjs#584]
The way the CLI currently accepts a template from stdin is a bit awkward in my opinion.

In scripting scenarios it's much more common that the context (data) is what's dynamic and piped from another command, while the template is fixed/static and resides in a file or as a literal in the script.

For example, imagine any command `acme` that has a `--json` argument to output its result as JSON. It would be a more natural fit with shell piping principles if you could just do:

```
acme --json | npx liquidjs --template some-template.liquid
```

Because things are currently the other way around, we must now instead do this:

```
acme --json > output.json
cat some-template.liquid | npm liquidjs output.json
```

If maintainers agree, I will contribute this in a PR.

Somewhat related to #583

**Comment by harttle** [comment]
I see your point. While it depends on whether you're data producer or template editor.

I think it's also OK to pass JSON data on STDIN, but make sure only do so when --template is specified so that it's backward compatible and we can publish this feature as a minor version.

**Comment by DaRosenberg** [comment]
Yep, good idea — I'll do so to maintain compatibility. 👍🏻 

Yeah I see your point about data producer vs. template editor. Still, I do think that if you're wanting to use the CLI, you're more likely to be varying the data than the template. Whereas if you're building a template editor tool or something where you want to vary the template, you're probably much more likely to be using the JS API.
