### ISSUE TITLE
Arrays should compare values

### ISSUE THREAD

**Issue by sebastienros** [harttle/liquidjs#589]
```liquid
{% assign people1 = "alice, bob, carol" | split: ", " -%}
{% assign people2 = "alice, bob, carol" | split: ", " -%}

{% if people1 == people2 %}true{%else%}false{% endif %}
```
This should return `true`

Shopify:
![image](https://user-images.githubusercontent.com/1165805/222246482-44302fae-1c5d-4a02-9905-8ac0f86664ae.png)

LiquidJs:
https://liquidjs.com/playground.html#eyUgYXNzaWduIHBlb3BsZTEgPSAiYWxpY2UsIGJvYiwgY2Fyb2wiIHwgc3BsaXQ6ICIsICIgLSV9CnslIGFzc2lnbiBwZW9wbGUyID0gImFsaWNlLCBib2IsIGNhcm9sIiB8IHNwbGl0OiAiLCAiIC0lfQoKeyUgaWYgcGVvcGxlMSA9PSBwZW9wbGUyICV9dHJ1ZXslZWxzZSV9ZmFsc2V7JSBlbmRpZiAlfQ==,e30=

**Comment by harttle** [comment]
Fixed in 10.6.1
