### ISSUE TITLE
Math.floor blocks float in divided_by filter

### ISSUE THREAD

**Issue by tim-phillips** [harttle/liquidjs#59]
In `filters.js`, [`divided_by`](https://github.com/harttle/liquidjs/blob/22b41fd1a89697d6c0e198b6ff9724a6dd5acb3c/filters.js#L36) is defined as `'divided_by': (v, arg) => Math.floor(v / arg)`.

However in the Liquid documentation it says that if given a float it will return a float (under the section "Controlling rounding"). `Math.floor` prevents that. 

https://shopify.github.io/liquid/filters/divided_by/

**Comment by harttle** [comment]
It seems JavaScript `Number` does not distinguish float and integer, which means it's may be not possible to be compliant with shopify.
AFAIK, either `Number.isInteger(x)`, `x%1`, or `x.toString()` cannot test float numbers like `1.0`. Any ideas?

**Comment by babenzele** [comment]
You're right, it seems that javascript cannot handle the `1.0` case.

**Comment by harttle** [comment]
Since we have `floor` and `ceil`, can we always return the float result as it is? This is not backward-compatible but makes sense. What do you think?

**Comment by babenzele** [comment]
I already added this to my project:

`liquid.registerFilter('divided_by', (v, arg) => v / arg)`

So yes, I agree with returning the float as is.

**Comment by harttle** [comment]
Now `divided_by`  always return the number as it is. When integers are expected, use`ceil`, `floor` and `round` filters. Since this fix is NOT backward-compatible, we bump a major version to @4.0.0.
