### ISSUE TITLE
docs: How to use drops?

### ISSUE THREAD

**Issue by harttle** [harttle/liquidjs#592]
### Discussed in https://github.com/harttle/liquidjs/discussions/591

<div type='discussions-op-text'>

<sup>Originally posted by **espen** March 13, 2023</sup>
Sorry if I missed this but I looked through the website and searched the repo and couldn't find any documentation on how to use drops. I use drops with Liquid Ruby and looking into how I can create and use a similar drop with LiquidJS.

Are there any drop usage examples? It would be helpful to see it even if there is no documentation on this.</div>

**Comment by AsadCSE** [comment]
any update on drops?

**Comment by harttle** [comment]
I'm putting together a doc for you guys, and wanted to say thanks to everyone tossing in drop-related questions. These threads are a solid starting point for the doc I'm working on.

Sorry for the delay 😄

**Comment by harttle** [comment]
Please visit https://liquidjs.com/tutorials/drops.html
