### ISSUE TITLE
Parser does not catch variable syntax error

### ISSUE THREAD

**Issue by prsnca** [harttle/liquidjs#60]
The original liquid ruby gem fails on parsing if this case is given:
`{{ user_name }`
and generates this error:
`Liquid syntax error: Variable '{{ user_name }' was not properly terminated with regexp: /\}\}/`
I would expect this parser to catch these syntax errors as well and return a ParseError.
When trying to parse something with this syntax error, the tokenizer returns 'nested endless hash' or i don't know how to name it :)
<img width="888" alt="screen shot 2018-02-28 at 10 56 31 am" src="https://user-images.githubusercontent.com/5849766/36778713-3fd4ee08-1c76-11e8-95e4-a94f760ff4c2.png">

I have looked through the config and haven't found anything that will help me :/
@harttle - I'm willing to contribute on this - just give me some guidance ;)

Thanks!

**Comment by harttle** [comment]
Currently the tokenizer uses a regex-based loop to find all *OutToken*s and *TagToken*s, and characters between them are parsed as *HTMLToken*s. So there's no exception through out for unmatched *output*s and *tags*.

I agree that the parse loop should be implemented manually. We'll have fine-grained control over that process, so we can throw the exceptions you expected.

You can find the source code for the tokenizer here: https://github.com/harttle/liquidjs/blob/master/src/tokenizer.js And test cases here: https://github.com/harttle/liquidjs/blob/master/test/tokenizer.js

**Comment by harttle** [comment]
Should be resolved along with #89 after re-implement the tokenizer.

**Comment by harttle** [comment]
Now supported since @7.1.0 by [this commit](https://github.com/harttle/liquidjs/commit/c33d8f6828b91fcd418095c99f27d3b7b19b404f). Closing.
