### ISSUE TITLE
dynamicPartials: false, include tag, and subdirectories

### ISSUE THREAD

**Issue by zachleat** [harttle/liquidjs#61]
Hi! Hello, me again—same person that filed #51. I would like the following `dynamicPartials: false` test cases to pass:

## dynamicPartials: false

`{% include subfolder/included.liquid %}` Fails
`{% include 'subfolder/included.liquid' %}` Single quotes, Fails
`{% include "subfolder/included.liquid" %}` Double quotes, Fails

## dynamicPartials: true (for comparison)

`{% include subfolder/included.liquid %}` Fails
`{% include 'subfolder/included.liquid' %}` Single quotes, Passes
`{% include "subfolder/included.liquid" %}` Double quotes, Passes

This would fix https://github.com/11ty/eleventy/issues/72 for me! Thank you!

**Comment by harttle** [comment]
Fixed @3.1.1

**Comment by zachleat** [comment]
Wow, thank you @harttle! Amazing!
