### ISSUE TITLE
Filter, parse object arguments bug

### ISSUE THREAD

**Issue by cmawhorter** [harttle/liquidjs#63]
There is a bug in the way object filter arguments are parsed when the key is named the same as the value.

Example: `foo: someval: someval` with context `{ someval: 'hello' }`

That should result in args that are `[ 'someval', 'hello' ]` but instead it results in `[ 'someval', 'someval' ]`

Here's a runkit that shows this: https://runkit.com/embed/auys4zba1gxn

I have it fixed in my fork.  That also includes tests, but I can't PR because I've made a ton of breaking changes.

https://github.com/stampr/liquidjs/blob/f24c8c49b66890b1c7ca6d332edfa082d9398a42/src/filter.js#L36-L43

**Comment by harttle** [comment]
Seems a misunderstanding to the render process. When invoked with a template string and the corresponding context, the liquid engine:

1. parses the string into template objects, consisting of tokens with their hierarchy. This is done by the parser and there's no concept of context at this stage.
2. renders the template objects with a given context, just like populating values into a format string.

For you case:

* The syntax `foo: someval: someval` is not correct. Arguments for a filter should be separated by `,` (comma). For example: https://shopify.github.io/liquid/filters/replace_first/
* The parsed arguments `['someval', 'someval']` can be further rendered to `['someval', 'hello']` if you call the render on it: https://github.com/harttle/liquidjs/blob/master/src/filter.js#L13

Generally, you'll not want to do that manually, just register a filter and the above process is ready to run. See: https://github.com/harttle/liquidjs#register-filters

**Comment by cmawhorter** [comment]
[This is the line causing the bug](https://github.com/harttle/liquidjs/blob/c6ff1f7911ca3aee277b3130020fd5be81465b90/src/filter.js#L39).  It checks for the occurrence of `someval:` globally within in the match.input (argList).  Since `someval:` _is_ in the argList, it incorrectly thinks it's a key, and wraps it in single quotes resulting in an arg that is equal to `'someval'` instead of `someval`.  

The args array would be: `[ '\'someval\'', '\'someval\'' ]` instead of `[ ''\'someval\', 'someval' ]`

To put that a different way -- 

- `{{ 'some.translation' | t: someval: someval, amount: '$3.23' }}`.  
- `some.translation = "{{ someval }}, your total is {{ amount }}"`

is rendered as "someval, your total is $3.23" instead of "hello, your total is $3.23".  

Since filter.render incorrectly wraps a value as a literal, evalValue then (correctly) treats it as a string resulting in incorrect output.

**Comment by harttle** [comment]
Sorry I didn't know there's a named parameter syntax for filters. Let's get it running then. Do you have a working version? Feel free to file a PR for this issue, and I can help if it breaks other cases.

**Comment by harttle** [comment]
There's a util for parsing key-value pairs: https://github.com/harttle/liquidjs/blob/master/src/tag.js#L6, hope it useful.

**Comment by cmawhorter** [comment]
I submitted a PR.  There are probably better impl but it is working for me.  Does that linked hash fn work against mixed input?  

Filter arguments can get pretty complex.  For example with shopify [img_url](https://help.shopify.com/themes/liquid/filters/url-filters#img_url), this is valid liquid: 

`{{ settings.favicon | img_url: '240x', scale: 2, format: 'pjpg' }}` 

and so is this with the width literal being at the end:

`{{ settings.favicon | img_url: scale: 2, format: 'pjpg', '240x' }}` 

With liquidjs, the argument order passed to the filter fn is the same as the designer writing the source liquid, which can be problematic.

With some filters, arg order is guaranteed and sometimes it isn't (shopify filter link_to vs shopify filter img_url).  I think there needs to be a more formal way of passing filter arguments to registered filter functions.

Maybe something like [yargs](https://github.com/yargs/yargs/blob/master/docs/api.md#argv)?  `img_url: (v, args)`,  and args would be: 

```
{ 
  _: [ '240px' ], 
  scale: 2,
  format: 'pjpg', 
}
```

**Comment by harttle** [comment]
> With liquidjs, the argument order passed to the filter fn is the same as the designer writing the source liquid, which can be problematic.

I agree. It's OK to have args passed as `yargs` format. I'll make a major release for that. Are you ready to submit your changes for #65 , it'll be great to have both #63 and #65 features in that release.
