### ISSUE TITLE
Bug in release artifact process?

### ISSUE THREAD

**Issue by aviflax** [harttle/liquidjs#651]
I just downloaded the release artifact (`liquid.browser.umd.js`) for both the 10.9.1 and 10.9.2 releases, and I found that the version numbers in the source are offset by -1.

In other words, in the 10.9.1 artifact I found this comment: `* liquidjs@10.9.0, https://github.com/harttle/liquidjs` and this statement: `var version = '10.9.0';`

and in the 10.9.2 artifact I found this comment: `* liquidjs@10.9.1, https://github.com/harttle/liquidjs` and this statement: `var version = '10.9.1';`

NBD, just letting you know.

**Comment by harttle** [comment]
@aviflax thank you for calling out!

I'm trying to fix this in https://github.com/harttle/liquidjs/commit/67a5b229ca9ccabb4aee42bbb5c9f03d4076786a . Let's see if we can make it working.

**Comment by harttle** [comment]
Ha! seems fixed:

![image](https://github.com/harttle/liquidjs/assets/4427974/245169cb-0fca-4ff9-b788-bec42355fbdc)

Closing, feel free to reopen if there's still problems on your side.

**Comment by aviflax** [comment]
Great! My pleasure. Nice work!
