### ISSUE TITLE
Order of `else` and `elsif` blocks

### ISSUE THREAD

**Issue by jg-rp** [harttle/liquidjs#672]
Hi,

Related to #670 and #671, Shopify/Liquid will silently ignore any `{% elsif %}` tags after the first `{% else %}`.

**Example template**

```liquid
{% if false %}a{% else %}b{% elsif true %}c{% endif %}
``` 

**Shopify/Liquid output**

```
b
```

**LiquidJS output**

```
c
```

**Comment by harttle** [comment]
fixed demo: https://liquidjs.com/playground.html#eyUgaWYgZmFsc2UgJX1heyUgZWxzZSAlfWJ7JSBlbHNpZiB0cnVlICV9Y3slIGVuZGlmICV9,e30=
