### ISSUE TITLE
strip_html filter does not remove elements that include attributes

### ISSUE THREAD

**Issue by paulrobertlloyd** [harttle/liquidjs#68]
The `strip_html` filter is not comparable to the same filter in the Ruby version. While Ruby Liquid removes all HTML elements, this implementation currently ignores any opening tag containing attributes.

Comparing the regex, we can see why. [Ruby Liquid](https://github.com/Shopify/liquid/blob/0c802aba175aefb5cfb7e40c13c892075e70ffa5/lib/liquid/standardfilters.rb#L104):

```ruby
def strip_html(input)
    empty = ''.freeze
    input.to_s.gsub(/<script.*?<\/script>/m, empty).gsub(/<!--.*?-->/m, empty).gsub(/<style.*?<\/style>/m, empty).gsub(/<.*?>/m, empty)
end
```

As well as covering `script`, `style` and comment tags, it also removes any string of characters starting with `<` and ending with `>`.

[Liquid JS](https://github.com/harttle/liquidjs/blob/master/filters.js#L69) on the other hand uses a different approach:

```js
'strip_html': v => stringify(v).replace(/<\/?\s*\w+\s*\/?>/g, ''),
```

My JavaScript skills are pretty rough, but I monkey patched this filter to use the following regex instead:

```js
str.replace(/<script.*?<\/script>|<!--.*?-->|<style.*?<\/style>|<.*?>/g, '')
```

This more closely matches that used in the Ruby implementation. Would a PR with this change be accepted at all?

Thanks,

Paul

**Comment by harttle** [comment]
It's welcome to make a PR for this. Being compatible to the Ruby version is one of the top priorities. Thanks for this spot!

**Comment by harttle** [comment]
Thanks @paulrobertlloyd , closing
