### ISSUE TITLE
Update website about dependency

### ISSUE THREAD

**Issue by sntran** [harttle/liquidjs#711]
The homepage states that LiquidJS is "written with zero npm dependency and no native binding". This is no longer true. Should the webpage be updated?

**Comment by harttle** [comment]
Good catch. Now we have 1 dependency for cli.

**Comment by harttle** [comment]
Updated by https://github.com/harttle/liquidjs/commit/d141c4bdd2113956c5f3da53f60e8602fcd4c9d6, closing. Thanks @sntran.
