### ISSUE TITLE
Generated strings in `include` statements aren't working

### ISSUE THREAD

**Issue by jdsteinbach** [harttle/liquidjs#72]
Using:
```sh
└─┬ @11ty/eleventy@0.3.4
  └── liquidjs@2.2.1
```

I'm using the following code to vary a background pattern based on the length of a page's title.

```liquid
{% assign image = title | size | modulo: 5 | plus: 1 %}
{% include bg-{{image}} %}
```

That works fine in Liquid (Ruby) - I was compiling the site with Jekyll previously. But I've recently moved to a site compiler (11ty) that uses `liquidjs` and that no longer works. The 11ty debugger throws the following error:

```sh
RenderError: ENOENT: Failed to lookup bg-.liquid in: _includes, line:7
```

If I print the image variable `{{image}}` right above the `include` statement, I get a number as expected. Inside the `include` statement, however, `image` ends up `undefined`, and I'm unable to compile the site.

Thanks for your help!

**Comment by jdsteinbach** [comment]
Follow-up note: I installed `liquidjs@4.0.0` instead of the older version expected by 11ty and the problem is still happening.

**Comment by harttle** [comment]
now supported on liquidjs@5.1.0, thanks for this spot!
