### ISSUE TITLE
Usage of global `performance` breaks on Node <16

### ISSUE THREAD

**Issue by vrugtehagel** [harttle/liquidjs#727]
This is a bug report originating from [an issue from 11ty/eleventy](https://github.com/11ty/eleventy/issues/3414).

LiquidJS uses the `performance` global in a few places, but to support Node versions before 16 it should be imported from the built-in [`'perf_hooks'`](https://nodejs.org/api/perf_hooks.html#perf_hooksperformance) module.

**Comment by uncenter** [comment]
Ahah we should have been in better communication. I've just opened https://github.com/harttle/liquidjs/issues/728!

**Comment by vrugtehagel** [comment]
Ah, haha! All good, will close this in favor of https://github.com/harttle/liquidjs/issues/728
