### ISSUE TITLE
v10.15.0 and later do not support Node.js v14/v15 due to `performance` usage introduced in #715

### ISSUE THREAD

**Issue by uncenter** [harttle/liquidjs#728]
#715 breaks support for Node.js v14 and 15 (which are [listed as supported versions](https://github.com/harttle/liquidjs/blob/ebc8daeec9b5e14e9ce8d43567cbc3bd84641924/package.json#L13-L15)) due to the introduction of code using `performance.now()` ([1](https://github.com/harttle/liquidjs/blob/ebc8daeec9b5e14e9ce8d43567cbc3bd84641924/src/context/context.ts#L46), [2](https://github.com/harttle/liquidjs/blob/ebc8daeec9b5e14e9ce8d43567cbc3bd84641924/src/render/render.ts#L19)), which is not available in the global context until Node.js v16 (previously it had to be imported manually with `const { performance } = require('perf_hooks')`.

Discovered via https://github.com/11ty/eleventy/issues/3414.

**Comment by harttle** [comment]
Thanks @uncenter @vrugtehagel , the PR is merged. I'll try to create a `node-version: 14` pipeline on GithubActions so it's checked.
