### ISSUE TITLE
Remove any-promise dependency

### ISSUE THREAD

**Issue by franciscop** [harttle/liquidjs#73]
Hi, I'd like to ask for a feature request: remove `any-promise` dependency. In their Readme it specifies:

> NOTE: You probably want native promises now

If you try to rollup `liquidjs` that bit will throw an error:

![window_not_defined](https://user-images.githubusercontent.com/2801252/41807316-68528506-7708-11e8-9e7e-996e29d77e8a.png)

This is because `any-promise` is using `window.Promise` straight away without checking that window exists first:

> https://github.com/kevinbeaty/any-promise/blob/master/register-shim.js#L10

So, even if you wrap liquidjs with UMD, this dependency is not properly wrapped and it will blow up.

**Comment by harttle** [comment]
I'll remove `any-promise`. It's already supported by major browsers and Node.js releases. But you're expected to use the entry file specified by `main` field in `package.json`.

**Comment by franciscop** [comment]
Yes, just realized that even if I mock window it won't work. The file in `"main"` is giving me a totally different set of trouble with rollup, let me check whether I can find any way of fixing it on my end first or if I can come with a PR somehow.

**Comment by harttle** [comment]
44b1aac breaks on Node.js 10: https://travis-ci.org/harttle/liquidjs/jobs/395832165 . It's a issue with the latest tschaub/mock-fs#238
