### ISSUE TITLE
Highlighting in docs is not working

### ISSUE THREAD

**Issue by vrugtehagel** [harttle/liquidjs#736]
The highlighting is broken (I think it has been for a little while). I looked into it, but I'm unfamiliar with Hexo and could not pinpoint the issue. However, deleting `docs/db.json` locally somehow fixes the issue. I'm not entirely sure why this happens, though, since the file is not checked into version control; so I would think it shouldn't happen on deployments. Perhaps the file is cached?

**Comment by harttle** [comment]
Yes the liquid language alone is broken, strange.

I changed the `_config.yml` and it's now fixed, not sure why this change is necessary. FYI: The `db.json` is a local cache, you'll need to remove it to let `_config.yml` changes take effect.
