### ISSUE TITLE
liquid.node.esm.js breaks in module context

### ISSUE THREAD

**Issue by wyozi** [harttle/liquidjs#739]
Hi, I'm trying to use liquidjs in a esm project. However, it fails in runtime with this error: `ReferenceError: require is not defined in ES module scope, you can use import instead`

The culprit seems to be this line in the built liquid.node.esm.js dist: `const requireResolve = require.resolve;` (that's line 1479 in v.10.16.4)

Using node version 21

**Comment by harttle** [comment]
Please try v10.16.5

**Comment by wyozi** [comment]
Thanks, seems to work now
