### ISSUE TITLE
cols parameter in tablerow is mandatory?

### ISSUE THREAD

**Issue by adisuryadi** [harttle/liquidjs#74]
Hi,
Is there any reason why the col parameter is mandatory on tablerow tag?

Didn't work:
```
<table>
{% tablerow product in collection.products %}
  {{ product.title }}
{% endtablerow %}
</table>
```

Works:
```
<table>
{% tablerow product in collection.products cols:1 %}
  {{ product.title }}
{% endtablerow %}
</table>
```
Base on official documentation section of [tablerow](https://shopify.github.io/liquid/tags/iteration/), it seems that we can skip it. 

Related test:
https://github.com/harttle/liquidjs/blob/master/test/tags/tablerow.js

**Comment by harttle** [comment]
You're right, it should be rendered in a single `<tr>` if `cols` not set. BTW, `table_row` should not output the `<table>` itself.

**Comment by harttle** [comment]
Have a look at this commit: 88fc057. I will publish a major version.
