### ISSUE TITLE
10.16.5 should not have been a minor release

### ISSUE THREAD

**Issue by vrugtehagel** [harttle/liquidjs#750]
Issues have been arising as a result of the new 10.16.5 release. I believe it should not have been a minor release, and I recommend rolling it back, releasing 10.16.6, and subsequently re-releasing 10.16.5 as 10.17.0.

Besides the new issues opened in this repository, Eleventy builds have come to a halt for many folks (see https://github.com/11ty/eleventy/issues/3425) since the import statement Eleventy uses is not quite compatible with the changes introduced by 10.16.5.

By rolling the change back and releasing 10.16.6, we can avoid issues within other packages that import liquidJS. Package managers usually choose to install the latest minor version and so the 10.16.6 would fix issues for folks that are having problems now with Eleventy or other dependants.

Re-releasing the ESM changes as 10.17.0 then gives the dependents time to adjust and upgrade whenever they are ready to do so.

**Comment by rdela** [comment]
I agree 10.6.5 should not have been a minor release. That said, worth mentioning it seems Eleventy was relying on outdated behavior and there is an [open PR](https://github.com/11ty/eleventy/pull/3426) to remedy that now: 

> Default export is removed from liquidjs a long time ago but it still work[ed] by CommonJS interop.
> 
> While 10.16.5 adds `exports.import` and `exports.require` to package.json which changed the imported bundle from cjs to mjs in this case, thus `default` no longer works.

https://github.com/11ty/eleventy/issues/3425#issuecomment-2316663404

And thank you for the quick response with 10.6.7 Jun!

**Comment by harttle** [comment]
@vrugtehagel reverted changes on latest release and added that esm feature to v11 milestone as it’s a breaking one.

**Comment by vrugtehagel** [comment]
Awesome @harttle , thank you so much for the speedy recovery!
