### ISSUE TITLE
getting current line number and template name from a filter

### ISSUE THREAD

**Issue by mohas** [harttle/liquidjs#762]
when using a custom filter it is very helpful to get the template name and current line that the filter is called in, is there a way to do that? so we can use it for logging purposes

**Comment by harttle** [comment]
Not yet, but I think it can be easily implemented. Still need further investigation, will post back before end of this week.

**Comment by harttle** [comment]
Published 10.18.0. You can get file name from `this.token.file`, and line/col from `this.token.begin`. Example here:

https://github.com/harttle/liquidjs/blob/d705888c8d46d9dd95fcb41c0fb7bfbaf647eddd/test/e2e/issues.spec.ts#L519-L525

**Comment by mohas** [comment]
Great work thanks
