### ISSUE TITLE
Filter where not completely compatible with Jekyll

### ISSUE THREAD

**Issue by lsolesen** [harttle/liquidjs#768]
I am transferring a site from Jekyll to 11ty. There I was hoping that where filter is working in the same way. 

I can get the baked in `where` filter to work with strings. However, it does not work if the key contains an array.

If my frontmatter has this:

```
tags:
  - Liquidjs
```

Then I cannot do:

`{% assign site_posts = collections.posts | where: "tags", "Liquidjs" %}`

It will work, if tags were just a string:

`tags: Liquidjs`

Making it compatible with Jekyll liquid where filter, would make transitions way easier.

**Comment by harttle** [comment]
I found Jekyll where is indeed different from that of Shopify/liquid. Added a `jekyllWhere` option to mimic Jekyll behaviour, please try `10.19.0`.
