### ISSUE TITLE
memoryLimit doesn't work in for tag

### ISSUE THREAD

**Issue by prd-dao-nguyen** [harttle/liquidjs#776]
Hey
This code will cause memory allocation failure. This will also break the playground.
```
{% for i in (1..1000000000) %} {{'a'}} {% endfor %}
```
Please check and tell me if there's any way to fix this!

Thank you!

**Comment by prd-dao-nguyen** [comment]
I ran some debug in the library and this code is the root cause:
```
function* evalRangeToken(token, ctx) {
    const low = yield evalToken(token.lhs, ctx);
    const high = yield evalToken(token.rhs, ctx);
    // console.log("Come here and die")
    return range(+low, +high + 1);
}
```
Should we add some check here?

**Comment by harttle** [comment]
Yes we already have cpu and mem limit mechanism in place, but not yet applied here.
Good catch!
