### ISSUE TITLE
Extract Liquid.js valid and invalid variables

### ISSUE THREAD

**Issue by SokratisVidros** [harttle/liquidjs#777]
Is there a built-in way to extract Liquid.js valid and invalid variables using LiquidJS.parse?

Effectively, we are looking for a function that looks like this:

```
async function extractVariables (content: string): {validVariables: string[], invalidVariables: string[]} {
// Parse content with Liquid
  return {
     validVariables,
     invalidVariables
  }
}
```

Thank you.

**Comment by jg-rp** [comment]
I've been working on PR #770 that might do what you need.

Please could you elaborate on what you mean by "valid" and "invalid" variables?

#770 uses the term "globals" (subject to change) to mean variables that are not in scope from tags like `assign` and arguments passed to block tags. The idea being that you would need to compare these _global_ variables to the variables you would pass to `Liquid.render()` in order to identify potentially erroneous names.

**Comment by SokratisVidros** [comment]
Hey @jg-rp, this is exactly what I am looking for. Let me know if you need any help with it so that we can merge it faster.

Currently, Liquid throws errors if an invalid syntax is used, for example, `This is an example text with a {{foo..bar}} invalid example`. By default, it fails fast on the first error. There is the option to get all errors at once, but another DX touch would be to not fail and return two sets of liquid variables, the valid and the invalid ones.

Let me know if this helps.

**Comment by jg-rp** [comment]
Thanks @SokratisVidros, that helps. Understanding different use cases for retrieving variables is half the battle.

In theory, I can imagine a fault tolerant tokenizer/parser that can resume scanning a template on some syntax errors, giving us the opportunity to report multiple invalid expressions. It would be a fairly massive change though and @harttle has already raised concerns about bundle size for browsers.

**Comment by SokratisVidros** [comment]
I see. The concern about the bundle size is valid, although it can only be validated during implementation by comparing before/after bundle sizes.

For the record, we ended up with [a similar in-house parser](https://github.com/novuhq/novu/pull/7192/files#diff-f2faf581fb7b9d8820f2ec03f939622c3f559d17cbdfd822e60d8284cdb92479R77). It would be awesome if all the Liquid internals were not exposed.
