### ISSUE TITLE
forloop.index is not rendered in express demo

### ISSUE THREAD

**Issue by dkbast** [harttle/liquidjs#79]
The todo Items should be numbered by the corresponding for index. Here is the link to the project on glitch: https://glitch.com/edit/#!/accessible-brazil?path=server.js:12:2

This is what I get:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Welcome to liquidjs!</title>
</head>
<body>
  <h1>Welcome to liquidjs!</h1>

  

<ul>
  
    <li> - fork and clone</li>
  
    <li> - make it better</li>
  
    <li> - make a pull request</li>
  
</ul>



  <footer> 
  Copyright @ 2016, Harttle
 </footer>
</body>
</html>
```

**Comment by harttle** [comment]
I don't think this line is valid:

```liquid
<li>{% include 'todo' id=forloop.index %}</li>
```

The [document](https://help.shopify.com/en/themes/liquid/tags/theme-tags) says:

```liquid
{% include 'snippet', my_variable: 'apples', my_other_variable: 'oranges' %}
```

**Comment by dkbast** [comment]
@harttle this template is from your express demo https://github.com/harttle/liquidjs/blob/master/demo/express/views/todolist.liquid

**Comment by harttle** [comment]
Oh! sorry for that, now fixed. Thank you for your report.
