### ISSUE TITLE
(How) Is it possible to get all available liquid variables from a template?

### ISSUE THREAD

**Issue by dkbast** [harttle/liquidjs#80]
I have a scenario where I have multiple liquid themes which can be interchanged. Instead of a dynamic database I use a CSV file, so I have to know all the variables upfront.
Let me explain this with a simplified example:

For these three Themes:
**Theme 1:**
title
text
image

**Theme 2:**
title 
text 
image

**Theme 3:**
image
subtitle

I would like to get the output of: **title, text, image, subtitle**

Is there a builtin routine I have missed? What would be the best way for accomplishing this?

**Comment by harttle** [comment]
As far as I know, there's no such feature in the Liquid template language. See https://github.com/Shopify/liquid/issues/685 But it's possible to achieve this by [registering a custom tag/filter](https://github.com/harttle/liquidjs#register-tags)

**Comment by timuster** [comment]
@harttle With this now being supported in Liquid ([see this comment](https://github.com/Shopify/liquid/issues/685#issuecomment-471499796)), is there any way to make it work with LiquidJS?

**Comment by harttle** [comment]
Not now. We don't have a parsetreevisitor yet. But I'm open for this
feature.

**Comment by FrankHeijden** [comment]
I am also looking for this feature, my use case is that I have to fetch an object as a variable, being able to know which variables are being referenced on that object would help greatly with only fetching what is necessary :)

**Comment by FrankHeijden** [comment]
nvm, just found out about this discussion: https://github.com/harttle/liquidjs/discussions/528
apparently there exists a `content` field on `Token`, however it is not defined in the type:
<img width="873" alt="Screenshot 2023-01-22 at 16 16 36" src="https://user-images.githubusercontent.com/22407829/213923547-872ce6b1-a709-41fd-af22-18f31d582c10.png">

**Comment by harttle** [comment]
@FrankHeijden I believe you came across a [DelimitedToken](https://github.com/harttle/liquidjs/blob/7f76e1311f02918748ec1744854951b0f8fee887/src/tokens/delimited-token.ts#L8) which is a subclass of `Token`.

I created a PR for astexplorer https://github.com/fkling/astexplorer/pull/680 , hopefully one day it'll be available on https://astexplorer.net/ website.

**Comment by TheSecurityDev** [comment]
I'm stuck on this issue as well. Is it possible or not?
