### ISSUE TITLE
Stringify?

### ISSUE THREAD

**Issue by ilg-ul** [harttle/liquidjs#81]
As far as I can see in `liquid.js` and `render.js`, the logic is:

```javascript
function stringify(val) {
  if (typeof val === 'string') return val;
  return JSON.stringify(val);
}
```

This is generally ok, except for objects which have a `toString()` function.

As far as I understood from the [MDN site](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString#Using_toString()_to_detect_object_class), the safe test for string would be:

```javascript
Object.prototype.toString.call(x) === '[object String]'
```

---

Until a fix will be available, a possible workaround is to add a getter:

```
  get toStr () {
    return this.toString()
  }
```

and in the template use it explicitly `{{ object.toStr }}`.

---

There is also a problem with `JSON.stringify()`, for complex objects it fails with `Converting circular structure to JSON`.

**Comment by harttle** [comment]
## Supporting toString

If we check `.toString` and use it if defined, it'll yield `[object Object]` in most cases.

Shopify/liquid does not support `to_s` either, cause its expected context type is HashSet. For object contexts, a [to_liquid](https://github.com/Shopify/liquid/blob/master/lib/liquid/context.rb#L186) method is expected (otherwise, it will raise an Error).

In our case it's trivial to implement a `to_liquid` since the context itself is an Object rather than a HashSet. It's more intuitive to use object in JavaScript.

I think we can change `to_liquid` a little, and use it to do the stuff you wanted, and use `util.inspect` if not defined. Thus never use `toString`. Other ideas?

## Bugs Regarding to Circular and Type Checking

String type checking and exceptions for circular objects are bugs, will be solved.

**Comment by ilg-ul** [comment]
> Other ideas?

I'm afraid my suggestion was not clear.

In JavaScript, testing for `typeof val === 'string'` is not enough, possibly not even correct. The [official](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString#Using_toString()_to_detect_object_class) test is `Object.prototype.toString.call(x) === '[object String]'`.

Thus, your code should read:

```javascript
function stringify(val) {
  if (Object.prototype.toString.call(val) === '[object String]') return val;
  return JSON.stringify(val);
}
```

**Comment by harttle** [comment]
I fixed string type checking here, as well as circular exception when calling `JSON.stringify`.

**Comment by ilg-ul** [comment]
Great! 

I'll test it these days and come back to you.

Thank you,

Liviu

**Comment by dmalan** [comment]
Just wanted to chime in to say that the [proposed support](https://github.com/harttle/liquidjs/commit/44c26fc577061520394cdccded85bb3fa4a46c59#diff-8d22c57a1fb31441cee9ba7ada4395f7R17) for `to_liquid` would indeed be quite helpful!

**Comment by ilg-ul** [comment]
I took a quick look at the commit and just wondering; if `.to_liquid()` is present, isn't it expected to override the string value?

in other words, should't the order of tests be reversed?

```javascript
function stringify (value) {
   if (value && typeof value.to_liquid === 'function') {
     return value.to_liquid()
   }
   if (isString(value)) {
     return value
   }
   // ...
}
```

And what if `.to_liquid()` does not return a string? Probably it should be silently ignored and the string value be used.

**Comment by harttle** [comment]
You're right, `to_liquid` should be tested first. As for `.to_liquid`, the official [to_liquid](https://github.com/Shopify/liquid/blob/a979b3ec950b6def8dab85bd1c5ecfb4c8b6fd04/lib/liquid/context.rb#L186) is part of variable lookup, thus both `HashMap` and `String` can be returned and rendered. This is a similar implementation by calling `stringify` recursively:

```javascript
function stringify (value) {
   if (value && typeof value.to_liquid === 'function') {
     return stringify(value.to_liquid())
   }
```

The only one tricky part is, in the shopify/liquid, `to_liquid` won't be called recursively, i.e. if `obj1.to_liquid` returns another `obj2`, it simply render `obj2` as `#<Object:0x00007f86960205e8>`, regardless `obj2.to_liquid`.

**Comment by ilg-ul** [comment]
Another detail, I tried to test `to_liquid()`, but the [stadard](https://standardjs.com) validator rejects it:

```
/.../xmake-js.git/lib/utils/source-tree.js:236:3: Identifier 'to_liquid' is not in camel case.
```

I know that this is subjective, but I prefer the strict checks of the 'standard' validator.

The Ruby `to_liquid()` should probably be `toLiquid()` in JavaScript.

Perhaps you can either use the CamelCase name, or both, if you think the Ruby name is also useful.

**Comment by harttle** [comment]
Both `to_liquid` and `toLiquid` supported, published @5.2.0

**Comment by ilg-ul** [comment]
Great, I'll update and use it.

Thank you,

Liviu

**Comment by dmalan** [comment]
Thank you!
