### ISSUE TITLE
Checking for null  values in conditionals

### ISSUE THREAD

**Issue by scottgeye** [harttle/liquidjs#82]
I'm trying render a template that has a conditional value that might be null and render text based on that condition.  At the same time I also want to throw errors if other variables don't exist.  When I turn on strict variable checking, an error gets thrown regardless if that variable is getting checked as part of condition or used for rendering. Without strict variables, null variables get rendered without error.

```
{% if test != null %}
{{test}}
{% else %}
blank
{% endif %}
```

Is there a way to allow for these type of conditionals and also check for null values that might be rendered?

Thanks.

**Comment by harttle** [comment]
`Undefined Variable` error is raised during lookup, so you can neither render it nor check it. An alternative approach is: register a new tag to tolerant lookup error, and do stuff what you want. An example here: https://jsfiddle.net/harttle/njkcrhm5/

**Comment by scottgeye** [comment]
Unfortunately, that won't work for me since I'm using liquid formatting to process input from a user, so the implementation would have to work with standard tags.

I did however come up with a quick and dirty workaround:

```
const rawContent = '{% if test != null %}{{test}}{% else %}blank{% endif %}';
const liquid = Liquid();
const liquidStrict = Liquid({ strict_variables: true });

let tempContent = rawContent.replace(/{{/g, '[[').replace(/}}/g, ']]');
const processedContent = await liquid.parseAndRender(tempContent, data);
tempContent = processedContent.replace(/\[\[/g, '{{').replace(/\]\]/g, '}}');
const content = await liquidStrict.parseAndRender(tempContent, data);
```

Here I effectively remove the variables from the initial parsing round by replacing braces with brackets and process without strict variables.  Then I add back the braces and process with strict variables.  

This gives me the desired effect of checking that only defined variables are used for rendering.

Thanks for help.
