### ISSUE TITLE
create-react-app minification error

### ISSUE THREAD

**Issue by GDownes** [harttle/liquidjs#83]
I'm attempting to use LiquidJS as a dependency in a create-react-app based application.

Upon create-react-app build(npm run build) creating the optimised production build fails on minification. 

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/liquidjs/src/util/assert.js:5
```

create-react-app doesn't handle ES6 dependencies.
Is there a compiled ES5 dependency available?

Details linked:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by dkelly93** [comment]
I am also having the same issue as GDownes. Did you ever find a solution for this?

**Comment by jilliankeenan** [comment]
I'm also having this issue! Would be nice to see a fix for this. Thanks

**Comment by harttle** [comment]
Try this prerelease version: liquidjs@5.3.0-0 and let me know if there're any problem

**Comment by GDownes** [comment]
Tested the prerelease version, fixed my issue
