### ISSUE TITLE
Images in Liquid

### ISSUE THREAD

**Issue by sltwtr-apps** [harttle/liquidjs#86]
What about image properties and filters?

For example: 
     
mobile_image.aspect_ratio 

mobile_image | img_url: '1x1', format: 'jpg' 

mobile_image.alt | escape

https://www.shopify.com/partners/blog/img-url-filter

**Comment by sltwtr-apps** [comment]
Thanks for the quick response, but I tend to disagree with your point of view.   Why would image manipulation be unsuitable for a template engine?  We are not talking about business logic.  This is independent of Shopify, although they do a nice job and being compatible would be great.

Can you explain the plugin API?   It sounds promising.

**Comment by harttle** [comment]
Your case is not business related, but [the img_url filter](https://help.shopify.com/en/themes/liquid/filters/url-filters#img_url) is. According to the Shopify website, this filter should also support `product`, `variant`, and `line_item` objects:

```javascript
{{ product | img_url: '100x100' }}
{{ variant | img_url: '720x720' }}
{{ line_item | img_url: '1024x' }}
```

We could implement the general part, which takes img url strings as input, but still it's not a standard `img_url` filter.

Actually, there's no clear boundary between what is business-related and what is not. This repo just takes the filters/tags from [The Liquid Template Language](https://shopify.github.io/liquid/) as built-ins, and ignores the ones only described in the [Shopify theme website](https://help.shopify.com/en/themes/liquid).

The plugin API can be something like this:

```javascript
// app file
import Liquid from 'liquidjs'
let liquid = new Liquid()
liquid.plugin(require('shopify-url-filters'))
// shopify-url-filters
export default function(liquid, Liquid) {
    liquid.registerFilter(...)
}
```
