### ISSUE TITLE
array index not parsed {{array[index]}}

### ISSUE THREAD

**Issue by loopal** [harttle/liquidjs#87]
in `{{array[index]}}`, if `index` is a variable. It is not rendered but neglected instead.
(output would be `array` instead of `array[index]`)

**Comment by reasonzhang** [comment]
Fix, see PR#88.
The type of `name` is changed thus `if (name.length)` will fail.

**Comment by harttle** [comment]
fixed on https://github.com/harttle/liquidjs/commit/5412c5a39f91bf60c6ead685dc4ac7db3ec81c82
