### ISSUE TITLE
String filters break when argument has reserved regex characters

### ISSUE THREAD

**Issue by timdmackey** [harttle/liquidjs#89]
String filters such as _split, remove,_ and _replace_ break when the filter argument has one of the following special characters in it:

`[
(
)
|`

Note that paired brackets `[]` and parentheses `()` do not break the regex filter. Other special characters `\ ^ $ . | ? * + { }` do not seem to throw an error, but since they are unescaped they could potentially cause unexpected results.

LiquidJS should have some sort of escaping function to prevent this from happening.

Note that this testing was down with the browser based version of liquidjs (https://unpkg.com/liquidjs@6.0.0/dist/liquid.min.js)

**Comment by harttle** [comment]
It's a bug related to the tokenizer, which treats `|` as filter separator literally. That tokenizer should be rewritten into a state of the art fashion as well.

**Comment by harttle** [comment]
Here's a jsbin demo for the bug: https://jsbin.com/jiyegez/edit?html,output
