### ISSUE TITLE
Getting started with NodeJs

### ISSUE THREAD

**Issue by C-Lodder** [harttle/liquidjs#90]
Hey, I am trying to get started with LiquidJs using Node (v8)

I installed the package using `npm i liquidjs --save-dev`

I've then wrapped a simple snippet taken from the Github docs inside a grunt task as shown below:

```
const Liquid = require('liquidjs');

grunt.registerTask('html', 'task description', () => {

    const engine = Liquid();

    engine
        .parseAndRender('{{name}}', {name: 'alice'})
        .then(console.log);
});
```

This should output ideally output "alice" in the terminal, but it doesn't. Grunt just says the task is `done`.

Am I losing the plot or simply missing something?

Any help would be appreciated.

**Comment by harttle** [comment]
It's a grunt issue, see: https://gruntjs.com/creating-tasks. This will work for your case:

```javascript
const Liquid = require('liquidjs');
const grunt = require('grunt');

grunt.registerTask('html', 'task description', function () {
    const engine = Liquid();
    const done = this.async();
    return engine
        .parseAndRender('{{name}}', {name: 'alice'})
        .then(console.log)
        .then(done, done);
});
```

Note the `function` instead of `=>`.

**Comment by C-Lodder** [comment]
Thank you
