### ISSUE TITLE
React JS Demo for liquid JS 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [harttle/liquidjs#94]
@harttle Great work on this repo, I really enjoy using liquidjs! 
   
Is it possible to integrate a React JS version/example into this repo? 
```
<ul>
  {products.collection.map((products) =>
     <li key={post._id}>
      {product.title}
      </li>
    )}
</ul>
```
```
{% for product in collection.products %}
   {{ product.title  }}
{% endfor %}
```
Something like 'url_decode ' would be nice to have within my react functions. 😄  
```
 {product.title | url_decode }
```

**Comment by harttle** [comment]
`url_decode` is supported now @6.1.0, but I don't understand what do you mean by `React JS version/example`. Is that a demo for liquidjs usage in ReactJS?

**Comment by stevenanthonyrevo** [comment]
Thank you 👍  @harttle 

Yes correct, a demo for `React JS` similar to [express](https://github.com/harttle/liquidjs/tree/master/demo/express).  

WIP ~ to have the ability to render liquid files into react components.. 
```
componentDidMount() {
  const string = this.state.body //.liquid file or`<h1>{{name | capitalize}}</h1>`
  const obj = this.state.data //json or {name : 'alice'}
  engine.parseAndRender(string, obj)
    .then((html) => {
      this.setState({ body: html })
    });
}
render() {
  <div>
     {this.state.body} //output: <h1>Alice</h1>
  </div> 
}
```
Any help would be greatly apriecated!
Happy Hacktoberfest  💻

**Comment by harttle** [comment]
It's great to have a react demo, any PR will be welcome when you done.
