### ISSUE TITLE
add Drop

### ISSUE THREAD

**Issue by ztp130213** [harttle/liquidjs#97]
Could you to add Drop to liquidjs? 
Like shopify [Drops](https://github.com/Shopify/liquid/wiki/Introduction-to-Drops).
I have used liquidjs in nodejs for a shop app, and I need Drops to push some unsureness  variablies into a template, for example, products[{id}], the id is not ensure.
Thanks for your great work @harttle

**Comment by harttle** [comment]
It seems that a Drop is just a plain Object which is already supported, except for the `liquid_method_missing` method.

Maybe I'm just not sure what Drop actually provides. Does a single `liquid_method_missing` method work for you? Does the Drop structure provide more than that?

**Comment by ztp130213** [comment]
用中文描述可以吗？英语比较菜，怕描述不清楚

**Comment by ztp130213** [comment]
用中文描述可以吗？英语比较菜，怕描述不清楚

**Comment by harttle** [comment]
可以的！关键把需求描述清楚。

**Comment by ztp130213** [comment]
好的。就是我在做一个电商建站网站，用的liquid模版，想实现的功能是在parse之前并不知道模版里需要哪些变量，只有在解析的时候才知道需要哪些变量。比如：
`{% for block in collections[collection_id].products %} `
我需要渲染一个商品专辑，但是在parse模版的时候，并不知道模版需要collections，解析到这一句的时候才知道，才通过Drop对象取拉取collections[collection_id]的数据。
不知道讲清楚了没有，如果不清楚，我明天再补充。

**Comment by danielfriis** [comment]
I'm also looking for this support. Primarily, I have objects in my dataset that requires custom functionality based on the object type.

For all of them, I need the `to_s` instance method, to define default behavior when the object is called directly.

For instance, I have an object `image` with attributes `url`, `width` and `height`, but when calling `{ image }` in my template, I need it to return the `url` attribute. I don't see that possible without the Drop logic?

**Comment by scottge** [comment]
Awesome!  Could you add an example in your readme about how to use drop?

**Comment by harttle** [comment]
Both `.to_s()` and `.liquid_method_missing()` are supported, see this [unit test](https://github.com/harttle/liquidjs/blob/master/test/unit/render.js#L72-L83) for details. I can add a e2e test case if that's not enough.

**Comment by scottge** [comment]
An e2e test case will be helpful :)
