### ISSUE TITLE
Could you create @types for this module? 

### ISSUE THREAD

**Issue by scottge** [harttle/liquidjs#98]
Could you create @types for this module so that it can be easily used in typescript?

**Comment by harttle** [comment]
A `index.d.ts` from @oott123 has been merged and published @6.2.0, try it!
If you still got problems, any revision is welcome. I'm not closing this issue for now.

**Comment by scottge** [comment]
Excellent!!! :)

If you can add the token type and this type, it will be truely perfect.

```
// TODO: tokens type; this type
```

**Comment by scottge** [comment]
It turns that I MUST use `import Liquid = require('liquidjs')` to import the module in order for it to work.   I cannot do import from.

**Comment by oott123** [comment]
Liquidjs is not a es module, so that you may HAVE to use the `require` form instead of regular import syntax. However, these types have some errors and I have no time to fix it. Maybe someone can take over it.

**Comment by harttle** [comment]
> I cannot do import from.

Now it should work, there's an demo located at [demo/typescript/index.ts](https://github.com/harttle/liquidjs/blob/master/demo/typescript/index.ts). Definitions for tagToken, remainTokens, scope, hash, etc are still not available, but maybe added latter.

Let me know if you have problems with the demo.

**Comment by scottge** [comment]
Types seems broken in the latest 7.0 release?  My ts project is complaining that could not find a declaration file for liquidjs.

**Comment by harttle** [comment]
Now it's fixed @7.0.1 and all methods should be typed already. Closing.
